export const ORCHESTRATION_WIZARD_UI_COPY = {
  sectionTitle: 'Roadmap input',
  sectionHint:
    'Confirm how you want to execute changes and the planning window. Coverage must match this audit’s execution plan.',
  coverageLabel: 'Coverage (from audit)',
  scenarioLabel: 'Change scenario',
  seasonLabel: 'Planning window',
  planHorizonLabel: 'Plan dates (optional)',
  planHorizonStartLabel: 'Start (YYYY-MM-DD)',
  planHorizonEndLabel: 'End (YYYY-MM-DD)',
  planHorizonHint:
    'When both dates are valid, seasonal buckets map the critical path onto this calendar window using your planning preset. Leave blank to use the length-based split only.',
  previewTitle: 'Preview',
  previewDomains: 'Domains in scope',
  previewScenario: 'Scenario',
  previewSeason: 'Window',
  previewLoading: 'Updating preview…',
  previewLanesIncluded: 'Lanes in scope',
  previewLanesCut: 'Lanes outside current coverage',
  previewWaitingList: 'Waiting list (not in this audit)',
  previewCompression: 'Execution compression hint',
  previewDensity: 'Planning density',
  roadmapVersionLabel: 'Roadmap version',
  confirmSaveManifest: 'Save manifest snapshot',
  compilePlan: 'Compile plan',
  compilePlanStatusCompiling: 'Compiling roadmap…',
  compilePlanStatusDone: 'Last compiled: pack v{version}',
  compilePlanStatusIdleHint: 'Compile saves a new manifest snapshot and rebuilds the orchestration pack.',
  saveManifestSnapshotOnly: 'Save manifest snapshot only',
  buildPack: 'Build orchestration pack',
  buildPackNeedsManifestSync: 'Save manifest changes before rebuilding roadmap',
  manifestSaved: 'Manifest snapshot saved',
  packBuilt: 'Orchestration pack saved',
  manifestDraftQueueBanner:
    'Delivery Board lane or owner hints are queued for signing. Save the manifest snapshot below to merge them into the roadmap contract.',
  manifestDraftLaneQueuedToast: 'Execution hint queued. Save manifest snapshot in Strategy Lab to sign it.',
  timelineManifestFlowTitle: 'Change roadmap coverage',
  timelineManifestFlowHint:
    'Preview manifest, save a snapshot, then build the next roadmap version (vN+1). Consultants complete this in Strategy Lab.',
  timelineManifestFlowCta: 'Open manifest flow in Strategy Lab',
  timelineManifestStaleCta: 'Manifest is stale — open Strategy Lab to confirm and rebuild',
} as const;
