export const INTAKE_TRACE_EDGE_GRAPH_UI_COPY = {
  emptyGraph: 'No nodes available for the graph.',
  intro: 'Graph view of question branching. Click a node to focus it and inspect dependencies.',
  actions: {
    showFullGraph: 'Show full graph',
    showPathOnly: 'Show root -> focused path only',
    expandFocusedSubtree: 'Expand focused subtree',
    collapseFocusedSubtree: 'Collapse focused subtree',
    expandAllSubtrees: 'Expand all subtrees',
    exportSvg: 'Export .svg',
    clearMultiSelect: 'Clear multi-select',
    unpinPath: 'Unpin path',
    pinFocusedPath: 'Pin focused path',
    hideBeforeAfter: 'Hide before/after',
    showBeforeAfter: 'Show before/after',
    advancedControls: 'Advanced controls',
    hideBaReview: 'Hide BA review',
    showBaReview: 'Show BA review',
    resetPreferences: 'Reset preferences',
    searchNode: 'Search node',
    searchPlaceholder: 'id or text',
    downstreamDepthFromFocus: 'Downstream depth from focus',
    legend: 'Legend',
    section: 'Section',
    collapsed: 'collapsed',
    shown: 'shown',
    inspectorTitle: 'Why hidden/visible (selected path)',
    inspectorHint: 'Click node = focus. Shift/Cmd/Ctrl + click = multi-select subgraph.',
    selectNodeToInspect: 'Select a node to inspect reasoning.',
    noReasonRows: 'No reason rows',
    baTitle: 'BA review: wording candidates',
    averageQuality: 'Average quality',
    showAllSeverities: 'Show all severities',
    showHighOnly: 'Show high severity only',
    exportReviewMarkdown: 'Export review .md',
    noWordingIssues: 'No obvious wording issues by heuristics.',
    qualityLabel: 'quality',
    statusLabel: 'status',
  },
  legendRows: [
    { status: 'required', tone: 'amber' },
    { status: 'visible', tone: 'blue' },
    { status: 'deferred', tone: 'violet' },
    { status: 'hidden', tone: 'gray' },
  ],
  beforeAfter: {
    before: 'before',
    after: 'after',
  },
  aria: {
    graphLabel: 'Intake branching edge graph',
    focusQuestionPrefix: 'Focus question',
  },
} as const;

