/**
 * Agent context slices — docs/QUESTION_BANK.md §5.
 * Canonical map of domain → question ids; ordered per bank in `question-bank.ts`.
 */
import type { IntakeSliceDomain } from './types.js';

export const DOMAIN_TO_QUESTIONS_RAW: Record<IntakeSliceDomain, readonly string[]> = {
  recon: ['a1', 'a2', 'a3', 'a4', 'a5', 'a6', 'a7'],
  tech_infrastructure: ['a5', 'c9', 'c1', 'c2', 'c6', 'd1', 'd_hotel_1', 'd_restaurant_1'],
  security_compliance: ['a6', 'e1', 'e2', 'e3', 'e4'],
  seo_digital: ['c3', 'c4', 'c7', 'c_nosite_1', 'c_nosite_2', 'c_nosite_3', 'b2'],
  ux_conversion: ['b1', 'b6', 'b7', 'c5', 'c6', 'b_services_1', 'b_health_1'],
  marketing_utp: [
    'b1',
    'b2',
    'b3',
    'b4',
    'b5',
    'b6',
    'b7',
    'c7',
    'c8',
    'b_hotel_1',
    'b_hotel_2',
    'b_restaurant_1',
    'b_realestate_1',
    'b_marine_1',
  ],
  automation_processes: [
    'd1',
    'd1a',
    'd1b',
    'd2',
    'd_automation_attempt',
    'd3',
    'd4',
    'd4a',
    'd4b',
    'd6',
    'd5',
    'a8',
    'f7',
    'd_hotel_1',
    'd_hotel_2',
    'd_realestate_1',
    'd_restaurant_1',
  ],
  strategy: [
    'f1',
    'f2',
    'f3',
    'f4',
    'f5',
    'f6',
    'f7',
    'f8',
    'a4',
    'a7',
    'a8',
    'b4',
    'b5',
    'b7',
    'd4a',
    'd4b',
    'd6',
  ],
};
