import {
  REPORT_PROFILE_MARKDOWN_FOCUS_TITLE,
  SCORE_LABELS,
  displayDomainLabel,
} from '@glc/intake-core';
import {
  REPORT_PROFILER_ONEPAGER_TOP_ISSUES_MAX,
  REPORT_PROFILER_ONEPAGER_TOP_QUICK_WINS_MAX,
  REPORT_PROFILER_OWNER_TOP_ISSUES_MAX,
  REPORT_PROFILER_OWNER_TOP_RECS_MAX,
} from '../../../../config/report-profiler-limits.js';
import { glcBrandSiteHostname } from '../../../../config/glc-brand-host.js';
import { REPORT_PROFILER_CONFIG } from '../../config.js';
import { getReportDomainCount } from '../../domain/coverage.js';
import type {
  DomainRow,
  MarkdownReportCoverage,
  ReportInput,
} from '../../types.js';
import {
  addCoverage,
  addDomainSections,
  addExecutiveSummary,
  addHeader,
  addRoadmap,
  addScorecard,
} from './sections.js';

function addFooter(lines: string[]): void {
  lines.push(`*Generated by GLC Audit Platform — ${glcBrandSiteHostname()}*`);
}

export function buildFullReport(
  input: ReportInput,
  domains: DomainRow[],
  company: string,
  coverage: MarkdownReportCoverage,
): string {
  const { audit, recon, strategy } = input;
  const lines: string[] = [];

  addHeader(lines, `IT Audit Report: ${company}`, audit, recon);
  addCoverage(lines, coverage);
  addExecutiveSummary(lines, strategy);
  addScorecard(lines, domains, audit.overall_score);
  addDomainSections(lines, domains, {
    showIssues: true,
    showRecs: true,
    showQuickWins: true,
    showConfidence: true,
  });
  addRoadmap(lines, strategy);
  addFooter(lines);

  return lines.join('\n');
}

export function buildOwnerReport(
  input: ReportInput,
  company: string,
  coverage: MarkdownReportCoverage,
): string {
  const { audit, recon, domains, strategy } = input;
  const lines: string[] = [];

  addHeader(lines, `Business Audit Summary: ${company}`, audit, recon);
  addCoverage(lines, coverage);
  addExecutiveSummary(lines, strategy);
  addScorecard(lines, domains, audit.overall_score);

  const topIssues = domains
    .flatMap((domain) => (domain.issues ?? []).map((issue) => ({ ...issue, domain: domain.domain_key })))
    .filter((issue) => issue.severity === 'critical' || issue.severity === 'high')
    .slice(0, REPORT_PROFILER_OWNER_TOP_ISSUES_MAX);

  if (topIssues.length > 0) {
    lines.push('## Priority Issues');
    lines.push('');
    for (const issue of topIssues) {
      lines.push(`### ${issue.title}`);
      lines.push(`**Domain:** ${displayDomainLabel(issue.domain)} · **Severity:** ${issue.severity.toUpperCase()}`);
      lines.push('');
      lines.push(issue.impact ?? '');
      lines.push('');
    }
    lines.push(REPORT_PROFILER_CONFIG.markdown.sectionDivider);
    lines.push('');
  }

  const recommendations = domains
    .flatMap((domain) =>
      (domain.recommendations ?? [])
        .filter((recommendation) => recommendation.priority === 'high')
        .map((recommendation) => ({ ...recommendation, domain: domain.domain_key })),
    )
    .slice(0, REPORT_PROFILER_OWNER_TOP_RECS_MAX);

  if (recommendations.length > 0) {
    lines.push(REPORT_PROFILER_CONFIG.markdown.sections.recommendedActions);
    lines.push('');
    for (const recommendation of recommendations) {
      lines.push(`- **${recommendation.title}** (${displayDomainLabel(recommendation.domain)})`);
      if (recommendation.estimated_cost || recommendation.estimated_time) {
        lines.push(
          `  Est. cost: ${recommendation.estimated_cost ?? '—'} · Time: ${recommendation.estimated_time ?? '—'}`,
        );
      }
    }
    lines.push('');
    lines.push(REPORT_PROFILER_CONFIG.markdown.sectionDivider);
    lines.push('');
  }

  addRoadmap(lines, strategy);
  addFooter(lines);
  return lines.join('\n');
}

export function buildDomainFocusedReport(
  input: ReportInput,
  domains: DomainRow[],
  company: string,
  focusTitle: string,
  coverage: MarkdownReportCoverage,
): string {
  const { audit, recon } = input;
  const lines: string[] = [];

  addHeader(lines, `${focusTitle}: ${company}`, audit, recon);
  addCoverage(lines, coverage);
  addScorecard(lines, domains, null);
  addDomainSections(lines, domains, {
    showIssues: true,
    showRecs: true,
    showQuickWins: true,
    showConfidence: false,
  });
  addFooter(lines);

  return lines.join('\n');
}

export function buildOnePagerReport(
  input: ReportInput,
  domains: DomainRow[],
  company: string,
  coverage: MarkdownReportCoverage,
): string {
  const { audit, recon, strategy } = input;
  const lines: string[] = [];

  lines.push(`# Audit Summary: ${company}`);
  lines.push('');
  lines.push(`**Date:** ${new Date(audit.created_at).toLocaleDateString('en-GB')} · **URL:** ${audit.company_url}`);
  if (recon?.industry) lines.push(`**Industry:** ${recon.industry}`);
  if (audit.overall_score) {
    lines.push(`**Overall Score:** ${audit.overall_score}/5 — ${SCORE_LABELS[Math.round(audit.overall_score)] ?? ''}`);
  }
  lines.push(
    `**Coverage:** ${Math.round(coverage.coverage_ratio * 100)}% (${coverage.covered_domains.length}/${getReportDomainCount()} domains)`,
  );
  lines.push('');
  lines.push(REPORT_PROFILER_CONFIG.markdown.sectionDivider);
  lines.push('');

  if (strategy?.executive_summary) {
    lines.push(strategy.executive_summary);
    lines.push('');
    lines.push(REPORT_PROFILER_CONFIG.markdown.sectionDivider);
    lines.push('');
  }

  lines.push(REPORT_PROFILER_CONFIG.markdown.sections.scorecardCompact);
  lines.push('');
  lines.push('| Domain | Score |');
  lines.push('|--------|-------|');
  for (const domain of domains) {
    if (domain.score) lines.push(`| ${displayDomainLabel(domain.domain_key)} | ${domain.score}/5 |`);
  }
  lines.push('');
  lines.push(REPORT_PROFILER_CONFIG.markdown.sectionDivider);
  lines.push('');

  const topIssues = domains
    .flatMap((domain) => domain.issues ?? [])
    .filter((issue) => issue.severity === 'critical' || issue.severity === 'high')
    .slice(0, REPORT_PROFILER_ONEPAGER_TOP_ISSUES_MAX);
  if (topIssues.length > 0) {
    lines.push(REPORT_PROFILER_CONFIG.markdown.sections.topIssues);
    lines.push('');
    for (const issue of topIssues) {
      lines.push(`- **[${issue.severity.toUpperCase()}]** ${issue.title}`);
    }
    lines.push('');
    lines.push(REPORT_PROFILER_CONFIG.markdown.sectionDivider);
    lines.push('');
  }

  const topQuickWins = domains
    .flatMap((domain) => domain.quick_wins ?? [])
    .slice(0, REPORT_PROFILER_ONEPAGER_TOP_QUICK_WINS_MAX);
  if (topQuickWins.length > 0) {
    lines.push(REPORT_PROFILER_CONFIG.markdown.sections.quickWins);
    lines.push('');
    for (const quickWin of topQuickWins) {
      lines.push(`- **${quickWin.title}**${quickWin.timeframe ? ` (${quickWin.timeframe})` : ''}`);
    }
    lines.push('');
  }

  addFooter(lines);
  return lines.join('\n');
}

export function buildFocusedByProfile(
  input: ReportInput,
  filteredDomains: DomainRow[],
  company: string,
  coverage: MarkdownReportCoverage,
  profile: 'tech' | 'marketing',
): string {
  return buildDomainFocusedReport(
    input,
    filteredDomains,
    company,
    REPORT_PROFILE_MARKDOWN_FOCUS_TITLE[profile],
    coverage,
  );
}
