/**
 * Stable machine-readable `code` values for JSON error responses.
 * Human `error` strings stay English for logs/clients until a full i18n catalog ships.
 *
 * Inventory: docs/API_ERRORS_INVENTORY.md (literal messages) + this file (typed codes).
 * User-facing English strings: `api-user-messages.en.json` / `api-user-messages.en.ts`.
 */

export const API_ERROR_CODES = {
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',

  /** SSRF / public URL validation (`PublicUrlNotAllowedError`) — granular reasons */
  PUBLIC_URL_INVALID: 'PUBLIC_URL_INVALID',
  PUBLIC_URL_CREDENTIALS_NOT_ALLOWED: 'PUBLIC_URL_CREDENTIALS_NOT_ALLOWED',
  PUBLIC_URL_PROTOCOL_NOT_ALLOWED: 'PUBLIC_URL_PROTOCOL_NOT_ALLOWED',
  PUBLIC_URL_HOST_NOT_ALLOWED: 'PUBLIC_URL_HOST_NOT_ALLOWED',
  PUBLIC_URL_ADDRESS_NOT_PUBLIC: 'PUBLIC_URL_ADDRESS_NOT_PUBLIC',
  PUBLIC_URL_DNS_DOES_NOT_RESOLVE: 'PUBLIC_URL_DNS_DOES_NOT_RESOLVE',
  PUBLIC_URL_DNS_NON_PUBLIC: 'PUBLIC_URL_DNS_NON_PUBLIC',
  PUBLIC_URL_DNS_REBINDING: 'PUBLIC_URL_DNS_REBINDING',
  PUBLIC_URL_NO_PUBLIC_WEBSITE: 'PUBLIC_URL_NO_PUBLIC_WEBSITE',
  PUBLIC_URL_REQUEST_FAILED: 'PUBLIC_URL_REQUEST_FAILED',
  PUBLIC_URL_TOO_MANY_REDIRECTS: 'PUBLIC_URL_TOO_MANY_REDIRECTS',

  IDEMPOTENCY_PAYLOAD_MISMATCH: 'IDEMPOTENCY_PAYLOAD_MISMATCH',
  /** `PATCH` requires `Idempotency-Key` header (Delivery Board card updates). */
  IDEMPOTENCY_KEY_REQUIRED: 'IDEMPOTENCY_KEY_REQUIRED',
  AUDIT_INITIALIZATION_FAILED: 'AUDIT_INITIALIZATION_FAILED',

  AUTH_MISSING_AUTHORIZATION: 'AUTH_MISSING_AUTHORIZATION',
  AUTH_INVALID_TOKEN: 'AUTH_INVALID_TOKEN',
  AUTH_AUTHENTICATION_FAILED: 'AUTH_AUTHENTICATION_FAILED',
  AUTH_NOT_AUTHENTICATED: 'AUTH_NOT_AUTHENTICATED',
  AUTH_PROFILE_LOAD_FAILED: 'AUTH_PROFILE_LOAD_FAILED',
  AUTH_PROFILE_CREATE_FAILED: 'AUTH_PROFILE_CREATE_FAILED',
  AUTH_PROFILE_UPDATE_FAILED: 'AUTH_PROFILE_UPDATE_FAILED',
  AUTH_PROFILE_LOOKUP_FAILED: 'AUTH_PROFILE_LOOKUP_FAILED',
  AUTH_ROLE_REQUIRED: 'AUTH_ROLE_REQUIRED',
  AUTH_GUEST_PORTAL_FORBIDDEN: 'AUTH_GUEST_PORTAL_FORBIDDEN',
  AUTH_REGISTERED_LOG_REQUIRED: 'AUTH_REGISTERED_LOG_REQUIRED',

  DISCOVER_ANSWERS_REQUIRED: 'DISCOVER_ANSWERS_REQUIRED',
  DISCOVER_MATURITY_INVALID: 'DISCOVER_MATURITY_INVALID',
  DISCOVER_FINDINGS_REQUIRED: 'DISCOVER_FINDINGS_REQUIRED',
  DISCOVER_SAVE_FAILED: 'DISCOVER_SAVE_FAILED',
  DISCOVER_DELETE_FAILED: 'DISCOVER_DELETE_FAILED',
  DISCOVER_UI_FRAGMENT_FAILED: 'DISCOVER_UI_FRAGMENT_FAILED',
  DISCOVER_ANALYTICS_PAYLOAD_INVALID: 'DISCOVER_ANALYTICS_PAYLOAD_INVALID',
  DISCOVER_ANALYTICS_STORE_FAILED: 'DISCOVER_ANALYTICS_STORE_FAILED',
  DISCOVER_ANALYTICS_ACCEPT_FAILED: 'DISCOVER_ANALYTICS_ACCEPT_FAILED',
  DISCOVER_LIST_FAILED: 'DISCOVER_LIST_FAILED',
  DISCOVER_INVALID_TOKEN: 'DISCOVER_INVALID_TOKEN',
  DISCOVER_SESSION_NOT_FOUND: 'DISCOVER_SESSION_NOT_FOUND',
  DISCOVER_LOAD_FAILED: 'DISCOVER_LOAD_FAILED',
  DISCOVER_CONTACT_EDIT_KEY_INVALID: 'DISCOVER_CONTACT_EDIT_KEY_INVALID',
  DISCOVER_CONTACT_FIELDS_REQUIRED: 'DISCOVER_CONTACT_FIELDS_REQUIRED',
  DISCOVER_CONTACT_EMPTY: 'DISCOVER_CONTACT_EMPTY',
  DISCOVER_CONTACT_SAVE_FAILED: 'DISCOVER_CONTACT_SAVE_FAILED',
  DISCOVER_CONTACT_NOT_ALLOWED: 'DISCOVER_CONTACT_NOT_ALLOWED',
  DISCOVER_CONVERT_FAILED: 'DISCOVER_CONVERT_FAILED',
  DISCOVER_ALREADY_CONVERTED: 'DISCOVER_ALREADY_CONVERTED',
  DISCOVER_FORBIDDEN_OWNER: 'DISCOVER_FORBIDDEN_OWNER',
  DISCOVER_CLAIM_CONFLICT: 'DISCOVER_CLAIM_CONFLICT',
  DISCOVER_LINK_CONFLICT: 'DISCOVER_LINK_CONFLICT',
  DISCOVER_INTAKE_READINESS_BLOCKED: 'DISCOVER_INTAKE_READINESS_BLOCKED',

  MARKETING_NAME_REQUIRED: 'MARKETING_NAME_REQUIRED',
  MARKETING_WEBSITE_OR_FLAG_REQUIRED: 'MARKETING_WEBSITE_OR_FLAG_REQUIRED',
  MARKETING_DEPTH_REQUIRED: 'MARKETING_DEPTH_REQUIRED',
  MARKETING_INVALID_RECOMMENDATION: 'MARKETING_INVALID_RECOMMENDATION',
  MARKETING_SAVE_FAILED: 'MARKETING_SAVE_FAILED',

  AUDITS_FORBIDDEN: 'AUDITS_FORBIDDEN',
  /** Consultant must accept the Data Processing Agreement before creating an audit (or approving a portal request). */
  AUDITS_DPA_REQUIRED: 'AUDITS_DPA_REQUIRED',
  AUDITS_OMIT_COMPANY_URL_WHEN_NO_PUBLIC_WEBSITE: 'AUDITS_OMIT_COMPANY_URL_WHEN_NO_PUBLIC_WEBSITE',
  AUDITS_COMPANY_URL_REQUIRED: 'AUDITS_COMPANY_URL_REQUIRED',
  AUDITS_COMPANY_URL_INVALID: 'AUDITS_COMPANY_URL_INVALID',
  AUDITS_COMPANY_URL_NOT_ALLOWED: 'AUDITS_COMPANY_URL_NOT_ALLOWED',
  AUDITS_CREATE_FAILED: 'AUDITS_CREATE_FAILED',
  AUDITS_LIST_FAILED: 'AUDITS_LIST_FAILED',
  AUDITS_NOT_FOUND: 'AUDITS_NOT_FOUND',
  AUDITS_FETCH_FAILED: 'AUDITS_FETCH_FAILED',
  AUDITS_UPGRADE_PAYLOAD_INVALID: 'AUDITS_UPGRADE_PAYLOAD_INVALID',
  AUDITS_UPGRADE_FAILED: 'AUDITS_UPGRADE_FAILED',
  AUDITS_UPGRADE_NOT_FREE_SNAPSHOT: 'AUDITS_UPGRADE_NOT_FREE_SNAPSHOT',
  AUDITS_UPGRADE_NOT_COMPLETED: 'AUDITS_UPGRADE_NOT_COMPLETED',
  AUDITS_UPGRADE_ACCESS_DENIED: 'AUDITS_UPGRADE_ACCESS_DENIED',
  AUDITS_UPGRADE_RESET_DOMAINS_FAILED: 'AUDITS_UPGRADE_RESET_DOMAINS_FAILED',
  AUDITS_UPGRADE_INIT_DOMAINS_FAILED: 'AUDITS_UPGRADE_INIT_DOMAINS_FAILED',
  AUDITS_UPGRADE_INIT_REVIEWS_FAILED: 'AUDITS_UPGRADE_INIT_REVIEWS_FAILED',
  AUDITS_UPGRADE_INIT_STRATEGY_FAILED: 'AUDITS_UPGRADE_INIT_STRATEGY_FAILED',
  AUDITS_DELETE_FAILED: 'AUDITS_DELETE_FAILED',
  AUDITS_BRIEF_SCHEMA_FAILED: 'AUDITS_BRIEF_SCHEMA_FAILED',
  AUDITS_BRIEF_ANALYTICS_PAYLOAD_INVALID: 'AUDITS_BRIEF_ANALYTICS_PAYLOAD_INVALID',
  AUDITS_BRIEF_ANALYTICS_STORE_FAILED: 'AUDITS_BRIEF_ANALYTICS_STORE_FAILED',
  AUDITS_BRIEF_ANALYTICS_ACCEPT_FAILED: 'AUDITS_BRIEF_ANALYTICS_ACCEPT_FAILED',
  AUDITS_BRIEF_GET_FAILED: 'AUDITS_BRIEF_GET_FAILED',
  AUDITS_CLIENT_PROJECT_CONTEXT_GET_FAILED: 'AUDITS_CLIENT_PROJECT_CONTEXT_GET_FAILED',
  AUDITS_INTAKE_FOLLOWUP_SUGGESTIONS_GET_FAILED: 'AUDITS_INTAKE_FOLLOWUP_SUGGESTIONS_GET_FAILED',
  AUDITS_BRIEF_HELP_CLIENT_ONLY: 'AUDITS_BRIEF_HELP_CLIENT_ONLY',
  AUDITS_BRIEF_HELP_ACCESS_DENIED: 'AUDITS_BRIEF_HELP_ACCESS_DENIED',
  AUDITS_BRIEF_HELP_WRONG_PHASE: 'AUDITS_BRIEF_HELP_WRONG_PHASE',
  AUDITS_BRIEF_HELP_FAILED: 'AUDITS_BRIEF_HELP_FAILED',
  AUDITS_BRIEF_RESPONSES_NOT_OBJECT: 'AUDITS_BRIEF_RESPONSES_NOT_OBJECT',
  AUDITS_BRIEF_COLLECTION_MODE_INVALID: 'AUDITS_BRIEF_COLLECTION_MODE_INVALID',
  AUDITS_BRIEF_SAVE_FAILED: 'AUDITS_BRIEF_SAVE_FAILED',
  AUDITS_BRIEF_VALIDATION_FAILED: 'AUDITS_BRIEF_VALIDATION_FAILED',
  AUDITS_ACCESS_DENIED: 'AUDITS_ACCESS_DENIED',
  STRATEGY_EXECUTION_PACK_DISABLED: 'STRATEGY_EXECUTION_PACK_DISABLED',
  AUDITS_STRATEGY_EXECUTION_PACK_NOT_READY: 'AUDITS_STRATEGY_EXECUTION_PACK_NOT_READY',
  AUDITS_STRATEGY_EXECUTION_PACK_PAYLOAD_INVALID: 'AUDITS_STRATEGY_EXECUTION_PACK_PAYLOAD_INVALID',
  AUDITS_STRATEGY_EXECUTION_PACK_FAILED: 'AUDITS_STRATEGY_EXECUTION_PACK_FAILED',
  AUDITS_STRATEGY_EXECUTION_PACK_LIST_FAILED: 'AUDITS_STRATEGY_EXECUTION_PACK_LIST_FAILED',
  AUDITS_STRATEGY_LAB_CONTEXT_PAYLOAD_INVALID: 'AUDITS_STRATEGY_LAB_CONTEXT_PAYLOAD_INVALID',
  AUDITS_STRATEGY_LAB_CONTEXT_FAILED: 'AUDITS_STRATEGY_LAB_CONTEXT_FAILED',
  AUDITS_ROADMAP_MANIFEST_PAYLOAD_INVALID: 'AUDITS_ROADMAP_MANIFEST_PAYLOAD_INVALID',
  AUDITS_ROADMAP_MANIFEST_EXECUTION_PLAN_MISMATCH: 'AUDITS_ROADMAP_MANIFEST_EXECUTION_PLAN_MISMATCH',
  AUDITS_ROADMAP_MANIFEST_SNAPSHOT_FAILED: 'AUDITS_ROADMAP_MANIFEST_SNAPSHOT_FAILED',
  AUDITS_ROADMAP_MANIFEST_LIST_FAILED: 'AUDITS_ROADMAP_MANIFEST_LIST_FAILED',
  AUDITS_ROADMAP_MANIFEST_PREVIEW_FAILED: 'AUDITS_ROADMAP_MANIFEST_PREVIEW_FAILED',
  AUDITS_ORCHESTRATION_PACK_NOT_READY: 'AUDITS_ORCHESTRATION_PACK_NOT_READY',
  AUDITS_ORCHESTRATION_PACK_PAYLOAD_INVALID: 'AUDITS_ORCHESTRATION_PACK_PAYLOAD_INVALID',
  AUDITS_ORCHESTRATION_PACK_FAILED: 'AUDITS_ORCHESTRATION_PACK_FAILED',
  AUDITS_ORCHESTRATION_PLAN_REQUIRES_REFINEMENT: 'AUDITS_ORCHESTRATION_PLAN_REQUIRES_REFINEMENT',
  AUDITS_ORCHESTRATION_PACK_STALE_VERSION: 'AUDITS_ORCHESTRATION_PACK_STALE_VERSION',
  ORCHESTRATION_PACK_API_DISABLED: 'ORCHESTRATION_PACK_API_DISABLED',
  /** Delivery Board operational mutations blocked (degraded orchestration pack input quality). */
  PLAN_BOARD_GOVERNANCE_BLOCKED: 'PLAN_BOARD_GOVERNANCE_BLOCKED',
  /**
   * Manual backlog cards cannot enter **in_progress** while strict appendix §2.3 enforcement is enabled
   * (`FEATURE_PLAN_BOARD_STRICT_MANUAL_IN_PROGRESS`).
   */
  PLAN_BOARD_MANUAL_IN_PROGRESS_BLOCKED: 'PLAN_BOARD_MANUAL_IN_PROGRESS_BLOCKED',
  /** `POST …/plan/board/reconcile/preview` when `FEATURE_PLAN_BOARD_RECONCILE_DIFF_PREVIEW` is off. */
  PLAN_BOARD_RECONCILE_PREVIEW_DISABLED: 'PLAN_BOARD_RECONCILE_PREVIEW_DISABLED',
  /** PATCH plan board `lane` disabled when Board → manifest draft queue is enabled (Epic 2.1-C). */
  PLAN_BOARD_LANE_MANIFEST_DRAFT_REQUIRED: 'PLAN_BOARD_LANE_MANIFEST_DRAFT_REQUIRED',
  /** Per-audit column policy API when `FEATURE_PLAN_BOARD_CUSTOM_COLUMNS` is off or audit owner lacks entitlement. */
  PLAN_BOARD_CUSTOM_COLUMNS_DISABLED: 'PLAN_BOARD_CUSTOM_COLUMNS_DISABLED',
  /** Persisted column policy JSON failed schema or semantic invariants (Epic 3). */
  PLAN_BOARD_COLUMN_POLICY_INVALID: 'PLAN_BOARD_COLUMN_POLICY_INVALID',
  /** Invalid or over-limit manifest draft revision queue write. */
  MANIFEST_DRAFT_REVISION_REJECTED: 'MANIFEST_DRAFT_REVISION_REJECTED',
  /** Companion endpoint disabled unless `FEATURE_MANIFEST_DRAFT_REVISIONS_FROM_BOARD`. */
  MANIFEST_DRAFT_REVISIONS_DISABLED: 'MANIFEST_DRAFT_REVISIONS_DISABLED',
  ORCHESTRATION_GOVERNANCE_CTAS_DISABLED: 'ORCHESTRATION_GOVERNANCE_CTAS_DISABLED',
  DIRECTOR_DEEP_DIVE_DISABLED: 'DIRECTOR_DEEP_DIVE_DISABLED',
  DIRECTOR_DEEP_DIVE_PAYLOAD_INVALID: 'DIRECTOR_DEEP_DIVE_PAYLOAD_INVALID',
  DIRECTOR_DEEP_DIVE_QUOTA_EXCEEDED: 'DIRECTOR_DEEP_DIVE_QUOTA_EXCEEDED',
  DIRECTOR_DEEP_DIVE_TOKEN_BUDGET_EXCEEDED: 'DIRECTOR_DEEP_DIVE_TOKEN_BUDGET_EXCEEDED',
  DIRECTOR_DEEP_DIVE_JOB_NOT_FOUND: 'DIRECTOR_DEEP_DIVE_JOB_NOT_FOUND',
  DIRECTOR_DEEP_DIVE_FAILED: 'DIRECTOR_DEEP_DIVE_FAILED',
  DIRECTOR_DEEP_DIVE_DEAD_LETTER: 'DIRECTOR_DEEP_DIVE_DEAD_LETTER',

  AUDIT_REQUEST_GUEST_FORBIDDEN: 'AUDIT_REQUEST_GUEST_FORBIDDEN',
  AUDIT_REQUEST_URL_OMIT_WHEN_NO_SITE: 'AUDIT_REQUEST_URL_OMIT_WHEN_NO_SITE',
  AUDIT_REQUEST_URL_OR_FLAG_REQUIRED: 'AUDIT_REQUEST_URL_OR_FLAG_REQUIRED',
  AUDIT_REQUEST_URL_NOT_ALLOWED: 'AUDIT_REQUEST_URL_NOT_ALLOWED',
  AUDIT_REQUEST_PRODUCT_MODE_INVALID: 'AUDIT_REQUEST_PRODUCT_MODE_INVALID',
  AUDIT_REQUEST_BRIEF_SNAPSHOT_INVALID: 'AUDIT_REQUEST_BRIEF_SNAPSHOT_INVALID',
  AUDIT_REQUEST_CREATE_FAILED: 'AUDIT_REQUEST_CREATE_FAILED',
  AUDIT_REQUEST_LIST_FAILED: 'AUDIT_REQUEST_LIST_FAILED',
  AUDIT_REQUEST_NOT_FOUND: 'AUDIT_REQUEST_NOT_FOUND',
  AUDIT_REQUEST_FETCH_FAILED: 'AUDIT_REQUEST_FETCH_FAILED',
  AUDIT_REQUEST_UPDATE_FAILED: 'AUDIT_REQUEST_UPDATE_FAILED',
  AUDIT_REQUEST_ACCESS_DENIED: 'AUDIT_REQUEST_ACCESS_DENIED',
  AUDIT_REQUEST_WRONG_STATUS_FOR_UPDATE: 'AUDIT_REQUEST_WRONG_STATUS_FOR_UPDATE',
  AUDIT_REQUEST_SUBMIT_MISSING_SITE: 'AUDIT_REQUEST_SUBMIT_MISSING_SITE',
  AUDIT_REQUEST_SUBMIT_NOT_DRAFT: 'AUDIT_REQUEST_SUBMIT_NOT_DRAFT',
  AUDIT_REQUEST_SUBMIT_FAILED: 'AUDIT_REQUEST_SUBMIT_FAILED',
  AUDIT_REQUEST_SUBMIT_WRONG_STATUS: 'AUDIT_REQUEST_SUBMIT_WRONG_STATUS',
  AUDIT_REQUEST_APPROVE_CLAIM_CONFLICT: 'AUDIT_REQUEST_APPROVE_CLAIM_CONFLICT',
  AUDIT_REQUEST_APPROVE_IN_PROGRESS: 'AUDIT_REQUEST_APPROVE_IN_PROGRESS',
  AUDIT_REQUEST_APPROVE_SEED_FAILED: 'AUDIT_REQUEST_APPROVE_SEED_FAILED',
  AUDIT_REQUEST_APPROVE_FAILED: 'AUDIT_REQUEST_APPROVE_FAILED',
  AUDIT_REQUEST_REJECT_WRONG_STATUS: 'AUDIT_REQUEST_REJECT_WRONG_STATUS',
  AUDIT_REQUEST_REJECT_FAILED: 'AUDIT_REQUEST_REJECT_FAILED',
  AUDIT_REQUEST_DELIVER_WRONG_STATUS: 'AUDIT_REQUEST_DELIVER_WRONG_STATUS',
  AUDIT_REQUEST_DELIVER_UPDATE_FAILED: 'AUDIT_REQUEST_DELIVER_UPDATE_FAILED',
  AUDIT_REQUEST_DELIVER_FAILED: 'AUDIT_REQUEST_DELIVER_FAILED',

  INCOMPLETE_INTAKE_VERSIONS: 'INCOMPLETE_INTAKE_VERSIONS',
  UNSUPPORTED_INTAKE_VERSION: 'UNSUPPORTED_INTAKE_VERSION',
  INTAKE_VERSION_CONFLICT: 'INTAKE_VERSION_CONFLICT',

  INTAKE_AUDIT_ID_FORMAT_INVALID: 'INTAKE_AUDIT_ID_FORMAT_INVALID',
  INTAKE_CREATE_LINK_FAILED: 'INTAKE_CREATE_LINK_FAILED',
  INTAKE_INVALID_TOKEN: 'INTAKE_INVALID_TOKEN',
  INTAKE_AUDIT_ID_REQUIRED: 'INTAKE_AUDIT_ID_REQUIRED',
  INTAKE_TOKEN_NOT_FOUND: 'INTAKE_TOKEN_NOT_FOUND',
  INTAKE_NOT_ALLOWED: 'INTAKE_NOT_ALLOWED',
  INTAKE_TOKEN_LINKED_CONFLICT: 'INTAKE_TOKEN_LINKED_CONFLICT',
  INTAKE_AUDIT_NOT_FOUND: 'INTAKE_AUDIT_NOT_FOUND',
  INTAKE_LINK_TOKEN_FAILED: 'INTAKE_LINK_TOKEN_FAILED',
  INTAKE_LINK_AUDIT_FAILED: 'INTAKE_LINK_AUDIT_FAILED',
  INTAKE_LIST_SUBMISSIONS_FAILED: 'INTAKE_LIST_SUBMISSIONS_FAILED',
  INTAKE_LINK_NOT_FOUND: 'INTAKE_LINK_NOT_FOUND',
  INTAKE_PRODUCT_MODE_INVALID: 'INTAKE_PRODUCT_MODE_INVALID',
  INTAKE_COLLECTION_MODE_INVALID: 'INTAKE_COLLECTION_MODE_INVALID',
  INTAKE_SURFACE_INVALID: 'INTAKE_SURFACE_INVALID',
  INTAKE_VERSION_TUPLE_UNSUPPORTED: 'INTAKE_VERSION_TUPLE_UNSUPPORTED',
  INTAKE_PLAN_TRACE_FAILED: 'INTAKE_PLAN_TRACE_FAILED',
  INTAKE_LINK_EXPIRED: 'INTAKE_LINK_EXPIRED',
  INTAKE_LOAD_FAILED: 'INTAKE_LOAD_FAILED',
  INTAKE_INTELLIGENCE_SNAPSHOT_FAILED: 'INTAKE_INTELLIGENCE_SNAPSHOT_FAILED',
  INTAKE_PREFILL_LOAD_FAILED: 'INTAKE_PREFILL_LOAD_FAILED',
  INTAKE_RESPONSES_REQUIRED: 'INTAKE_RESPONSES_REQUIRED',
  INTAKE_RESPONSES_SCHEMA_INVALID: 'INTAKE_RESPONSES_SCHEMA_INVALID',
  INTAKE_SAVE_RESPONSES_FAILED: 'INTAKE_SAVE_RESPONSES_FAILED',
  INTAKE_PREBRIEF_INCOMPLETE: 'INTAKE_PREBRIEF_INCOMPLETE',
  /** Baseline identity fields missing for `POST …/brief/intelligence-snapshot` with `{ early_capture: true }`. */
  INTAKE_EARLY_CAPTURE_INCOMPLETE: 'INTAKE_EARLY_CAPTURE_INCOMPLETE',
  /** Authenticated early snapshot disabled via `FEATURE_BRIEF_EARLY_INTELLIGENCE_SNAPSHOT`. */
  INTAKE_EARLY_CAPTURE_DISABLED: 'INTAKE_EARLY_CAPTURE_DISABLED',
  /** Early capture is limited to consultant-created audits (`client_id` null). */
  INTAKE_EARLY_CAPTURE_FORBIDDEN: 'INTAKE_EARLY_CAPTURE_FORBIDDEN',
  INTAKE_PREBRIEF_AUDIT_OWNER_MISMATCH: 'INTAKE_PREBRIEF_AUDIT_OWNER_MISMATCH',

  /** Platform-admin token-budget top-up: invalid delta (out of allowed range) or missing fields. */
  AUDITS_TOKEN_BUDGET_TOPUP_INVALID: 'AUDITS_TOKEN_BUDGET_TOPUP_INVALID',
  /** Platform-admin token-budget top-up: RPC failed (DB-level error or audit not found). */
  AUDITS_TOKEN_BUDGET_TOPUP_FAILED: 'AUDITS_TOKEN_BUDGET_TOPUP_FAILED',

  AUDITS_BRIEF_CLONE_DISABLED: 'AUDITS_BRIEF_CLONE_DISABLED',
  AUDITS_BRIEF_CLONE_PAYLOAD_INVALID: 'AUDITS_BRIEF_CLONE_PAYLOAD_INVALID',
  AUDITS_BRIEF_CLONE_FORBIDDEN: 'AUDITS_BRIEF_CLONE_FORBIDDEN',
  AUDITS_BRIEF_CLONE_SOURCE_EMPTY: 'AUDITS_BRIEF_CLONE_SOURCE_EMPTY',
  AUDITS_BRIEF_CLONE_FAILED: 'AUDITS_BRIEF_CLONE_FAILED',

  INTAKE_TRACE_ANALYTICS_PAYLOAD_INVALID: 'INTAKE_TRACE_ANALYTICS_PAYLOAD_INVALID',
  INTAKE_TRACE_ANALYTICS_STORE_FAILED: 'INTAKE_TRACE_ANALYTICS_STORE_FAILED',
  INTAKE_TRACE_ANALYTICS_ACCEPT_FAILED: 'INTAKE_TRACE_ANALYTICS_ACCEPT_FAILED',
  INTAKE_TRACE_WORDING_LOAD_FAILED: 'INTAKE_TRACE_WORDING_LOAD_FAILED',
  INTAKE_TRACE_WORDING_PAYLOAD_INVALID: 'INTAKE_TRACE_WORDING_PAYLOAD_INVALID',
  INTAKE_TRACE_WORDING_UPDATE_FAILED: 'INTAKE_TRACE_WORDING_UPDATE_FAILED',
  INTAKE_TRACE_WORDING_SAVE_FAILED: 'INTAKE_TRACE_WORDING_SAVE_FAILED',
  INTAKE_TRACE_PUBLISH_PAYLOAD_INVALID: 'INTAKE_TRACE_PUBLISH_PAYLOAD_INVALID',
  INTAKE_TRACE_PUBLISH_FAILED: 'INTAKE_TRACE_PUBLISH_FAILED',
  INTAKE_TRACE_ROLLBACK_PAYLOAD_INVALID: 'INTAKE_TRACE_ROLLBACK_PAYLOAD_INVALID',
  INTAKE_TRACE_ROLLBACK_FAILED: 'INTAKE_TRACE_ROLLBACK_FAILED',
  INTAKE_TRACE_PUBLICATION_LOG_QUERY_INVALID: 'INTAKE_TRACE_PUBLICATION_LOG_QUERY_INVALID',
  INTAKE_TRACE_PUBLICATION_LOG_FAILED: 'INTAKE_TRACE_PUBLICATION_LOG_FAILED',

  NOTIFICATIONS_LIST_FAILED: 'NOTIFICATIONS_LIST_FAILED',
  NOTIFICATIONS_UNREAD_COUNT_FAILED: 'NOTIFICATIONS_UNREAD_COUNT_FAILED',
  NOTIFICATIONS_NOT_FOUND: 'NOTIFICATIONS_NOT_FOUND',
  NOTIFICATIONS_MARK_READ_FAILED: 'NOTIFICATIONS_MARK_READ_FAILED',
  NOTIFICATIONS_MARK_ALL_FAILED: 'NOTIFICATIONS_MARK_ALL_FAILED',

  PLATFORM_SELF_SERVE_LOAD_FAILED: 'PLATFORM_SELF_SERVE_LOAD_FAILED',
  PLATFORM_ADMIN_ONLY: 'PLATFORM_ADMIN_ONLY',
  PLATFORM_OWNER_REQUIRED: 'PLATFORM_OWNER_REQUIRED',
  PLATFORM_OWNER_UUID_INVALID: 'PLATFORM_OWNER_UUID_INVALID',
  PLATFORM_OWNER_NOT_CONSULTANT: 'PLATFORM_OWNER_NOT_CONSULTANT',
  PLATFORM_SELF_SERVE_PERSIST_FAILED: 'PLATFORM_SELF_SERVE_PERSIST_FAILED',
  PLATFORM_SELF_SERVE_UPDATE_FAILED: 'PLATFORM_SELF_SERVE_UPDATE_FAILED',
  PLATFORM_PAYLOAD_INVALID: 'PLATFORM_PAYLOAD_INVALID',
  PLATFORM_RECOMPUTE_IN_PROGRESS: 'PLATFORM_RECOMPUTE_IN_PROGRESS',
  PLATFORM_RECOMPUTE_LOCK_UNAVAILABLE: 'PLATFORM_RECOMPUTE_LOCK_UNAVAILABLE',
  PLATFORM_CONSULTANT_ALLOWLIST_LOAD_FAILED: 'PLATFORM_CONSULTANT_ALLOWLIST_LOAD_FAILED',
  PLATFORM_CONSULTANT_ALLOWLIST_EMAIL_INVALID: 'PLATFORM_CONSULTANT_ALLOWLIST_EMAIL_INVALID',
  PLATFORM_CONSULTANT_ALLOWLIST_ADD_FAILED: 'PLATFORM_CONSULTANT_ALLOWLIST_ADD_FAILED',
  PLATFORM_CONSULTANT_ALLOWLIST_DUPLICATE: 'PLATFORM_CONSULTANT_ALLOWLIST_DUPLICATE',
  PLATFORM_CONSULTANT_ALLOWLIST_REMOVE_FAILED: 'PLATFORM_CONSULTANT_ALLOWLIST_REMOVE_FAILED',

  PROFILE_LOAD_FAILED: 'PROFILE_LOAD_FAILED',
  PROFILE_PAYLOAD_INVALID: 'PROFILE_PAYLOAD_INVALID',
  PROFILE_UPDATE_FAILED: 'PROFILE_UPDATE_FAILED',
  PROFILE_LEGAL_CONSENTS_LOAD_FAILED: 'PROFILE_LEGAL_CONSENTS_LOAD_FAILED',
  PROFILE_LEGAL_CONSENTS_SAVE_FAILED: 'PROFILE_LEGAL_CONSENTS_SAVE_FAILED',
  PROFILE_LEGAL_CONSENTS_PAYLOAD_INVALID: 'PROFILE_LEGAL_CONSENTS_PAYLOAD_INVALID',

  REPORTS_AUDIT_NOT_FOUND: 'REPORTS_AUDIT_NOT_FOUND',
  REPORTS_GENERATE_FAILED: 'REPORTS_GENERATE_FAILED',

  SELF_SERVE_OWNER_UNAVAILABLE: 'SELF_SERVE_OWNER_UNAVAILABLE',

  SNAPSHOT_QUOTA_READ_FAILED: 'SNAPSHOT_QUOTA_READ_FAILED',
  SNAPSHOT_TOKEN_REQUIRED: 'SNAPSHOT_TOKEN_REQUIRED',
  SNAPSHOT_NOT_FOUND: 'SNAPSHOT_NOT_FOUND',
  SNAPSHOT_TOKEN_EXPIRED: 'SNAPSHOT_TOKEN_EXPIRED',
  SNAPSHOT_CLAIM_FAILED: 'SNAPSHOT_CLAIM_FAILED',
  SNAPSHOT_COMPANY_URL_REQUIRED: 'SNAPSHOT_COMPANY_URL_REQUIRED',
  SNAPSHOT_CREATE_FAILED: 'SNAPSHOT_CREATE_FAILED',
  SNAPSHOT_INIT_ROLLBACK: 'SNAPSHOT_INIT_ROLLBACK',
  SNAPSHOT_START_FAILED: 'SNAPSHOT_START_FAILED',
  SNAPSHOT_RESOURCE_NOT_FOUND: 'SNAPSHOT_RESOURCE_NOT_FOUND',
  SNAPSHOT_METRICS_FAILED: 'SNAPSHOT_METRICS_FAILED',
  SNAPSHOT_HOST_REQUIRED: 'SNAPSHOT_HOST_REQUIRED',
  SNAPSHOT_COMPARE_SELF_URL_REQUIRED: 'SNAPSHOT_COMPARE_SELF_URL_REQUIRED',
  SNAPSHOT_COMPARE_COMPETITOR_URL_REQUIRED: 'SNAPSHOT_COMPARE_COMPETITOR_URL_REQUIRED',
  SNAPSHOT_COMPARE_FAILED: 'SNAPSHOT_COMPARE_FAILED',
  SNAPSHOT_PURGE_FAILED: 'SNAPSHOT_PURGE_FAILED',
  SNAPSHOT_INVALID_TOKEN: 'SNAPSHOT_INVALID_TOKEN',
  SNAPSHOT_FETCH_FAILED: 'SNAPSHOT_FETCH_FAILED',
  /** Poll/status when a free snapshot pipeline ended in `failed` (legacy body uses string `SNAPSHOT_FAILED`). */
  SNAPSHOT_FAILED: 'SNAPSHOT_FAILED',
  /** Claim would overwrite another user's attachment */
  SNAPSHOT_CLAIM_CONFLICT: 'SNAPSHOT_CLAIM_CONFLICT',
  /** @deprecated Prefer granular `PUBLIC_URL_*` codes from `PublicUrlNotAllowedError` (snapshot route returns those). */
  SNAPSHOT_INVALID_COMPANY_URL: 'INVALID_COMPANY_URL',
  /** Per-domain fresh-scan cooldown for free tool */
  SNAPSHOT_DOMAIN_FRESH_COOLDOWN: 'DOMAIN_FRESH_COOLDOWN',

  PIPELINE_FORBIDDEN: 'PIPELINE_FORBIDDEN',
  PIPELINE_AUDIT_NOT_FOUND: 'PIPELINE_AUDIT_NOT_FOUND',
  PIPELINE_ACCESS_DENIED: 'PIPELINE_ACCESS_DENIED',
  PIPELINE_ALREADY_STARTED: 'PIPELINE_ALREADY_STARTED',
  /** Intake diagnostic readiness gate — paid audit pipeline start blocked until context meets ADR baseline. */
  PIPELINE_INTAKE_READINESS_BLOCKED: 'PIPELINE_INTAKE_READINESS_BLOCKED',
  PIPELINE_TOKEN_BUDGET_EXCEEDED: 'PIPELINE_TOKEN_BUDGET_EXCEEDED',
  PIPELINE_START_CLAIM_CONFLICT: 'PIPELINE_START_CLAIM_CONFLICT',
  PIPELINE_PHASE_IN_PROGRESS: 'PIPELINE_PHASE_IN_PROGRESS',
  PIPELINE_ALL_PHASES_COMPLETE: 'PIPELINE_ALL_PHASES_COMPLETE',
  PIPELINE_REVIEW_PENDING: 'PIPELINE_REVIEW_PENDING',
  PIPELINE_NEXT_CLAIM_CONFLICT: 'PIPELINE_NEXT_CLAIM_CONFLICT',
  PIPELINE_PHASE_REQUIRED: 'PIPELINE_PHASE_REQUIRED',
  PIPELINE_PHASE_OUT_OF_RANGE: 'PIPELINE_PHASE_OUT_OF_RANGE',
  PIPELINE_PHASE_NOT_AVAILABLE_FOR_MODE: 'PIPELINE_PHASE_NOT_AVAILABLE_FOR_MODE',
  PIPELINE_ALREADY_TERMINAL: 'PIPELINE_ALREADY_TERMINAL',
  PIPELINE_ALREADY_CANCELLED: 'PIPELINE_ALREADY_CANCELLED',
  PIPELINE_RETRY_CLAIM_CONFLICT: 'PIPELINE_RETRY_CLAIM_CONFLICT',
  PIPELINE_STOP_CLAIM_CONFLICT: 'PIPELINE_STOP_CLAIM_CONFLICT',
  PIPELINE_STATUS_FAILED: 'PIPELINE_STATUS_FAILED',
  PIPELINE_QUALITY_GATE_FETCH_FAILED: 'PIPELINE_QUALITY_GATE_FETCH_FAILED',
  PIPELINE_REVIEW_APPROVE_FAILED: 'PIPELINE_REVIEW_APPROVE_FAILED',
  PIPELINE_QUALITY_GATE_REQUIRES_NOTES: 'PIPELINE_QUALITY_GATE_REQUIRES_NOTES',
  PIPELINE_START_FAILED: 'PIPELINE_START_FAILED',
  PIPELINE_NEXT_FAILED: 'PIPELINE_NEXT_FAILED',
  PIPELINE_RETRY_FAILED: 'PIPELINE_RETRY_FAILED',
  PIPELINE_STOP_FAILED: 'PIPELINE_STOP_FAILED',
  /** Platform-only: audit must be `cancelled` to clear stop and return to a claimable state. */
  PIPELINE_RESUME_NOT_CANCELLED: 'PIPELINE_RESUME_NOT_CANCELLED',
  PIPELINE_RESUME_CLAIM_CONFLICT: 'PIPELINE_RESUME_CLAIM_CONFLICT',
  PIPELINE_RESUME_FAILED: 'PIPELINE_RESUME_FAILED',

  AUDIT_CREATE_RATE_LIMITED: 'AUDIT_CREATE_RATE_LIMITED',
  PIPELINE_RATE_LIMITED: 'PIPELINE_RATE_LIMITED',
  GENERAL_API_RATE_LIMITED: 'GENERAL_API_RATE_LIMITED',
  REPORT_PDF_RATE_LIMITED: 'REPORT_PDF_RATE_LIMITED',
  BENCHMARK_RECOMPUTE_RATE_LIMITED: 'BENCHMARK_RECOMPUTE_RATE_LIMITED',
  COMPARE_RATE_LIMITED: 'COMPARE_RATE_LIMITED',
  SNAPSHOT_PUBLIC_RATE_LIMITED: 'SNAPSHOT_PUBLIC_RATE_LIMITED',
  INTAKE_LEGACY_RATE_LIMITED: 'INTAKE_LEGACY_RATE_LIMITED',
  DISCOVER_CREATE_RATE_LIMITED: 'DISCOVER_CREATE_RATE_LIMITED',
  DISCOVER_READ_RATE_LIMITED: 'DISCOVER_READ_RATE_LIMITED',
  DISCOVER_ANALYTICS_RATE_LIMITED: 'DISCOVER_ANALYTICS_RATE_LIMITED',
  BRIEF_PUBLIC_CREATE_RATE_LIMITED: 'BRIEF_PUBLIC_CREATE_RATE_LIMITED',
  BRIEF_PUBLIC_READ_RATE_LIMITED: 'BRIEF_PUBLIC_READ_RATE_LIMITED',
  BRIEF_PUBLIC_WRITE_RATE_LIMITED: 'BRIEF_PUBLIC_WRITE_RATE_LIMITED',
  INTAKE_READ_RATE_LIMITED: 'INTAKE_READ_RATE_LIMITED',
  INTAKE_WRITE_RATE_LIMITED: 'INTAKE_WRITE_RATE_LIMITED',
  MARKETING_BRIEF_RATE_LIMITED: 'MARKETING_BRIEF_RATE_LIMITED',
  LOG_INGEST_RATE_LIMITED: 'LOG_INGEST_RATE_LIMITED',
  SNAPSHOT_LOG_RATE_LIMITED: 'SNAPSHOT_LOG_RATE_LIMITED',

  BENCHMARKS_FEATURE_DISABLED: 'BENCHMARKS_FEATURE_DISABLED',
  BENCHMARK_SNAPSHOT_NOT_FOUND: 'BENCHMARK_SNAPSHOT_NOT_FOUND',
  BENCHMARK_PERIOD_INVALID: 'BENCHMARK_PERIOD_INVALID',
  BENCHMARK_RECOMPUTE_UNAUTHORIZED: 'BENCHMARK_RECOMPUTE_UNAUTHORIZED',
  BENCHMARK_RECOMPUTE_NOT_CONFIGURED: 'BENCHMARK_RECOMPUTE_NOT_CONFIGURED',
} as const;

export type ApiErrorCode = (typeof API_ERROR_CODES)[keyof typeof API_ERROR_CODES];

export type ApiErrorJsonBody = {
  code: ApiErrorCode;
  error: string;
  details?: unknown;
  /** Present on some 409 discovery responses */
  audit_id?: string | null;
  /** Present on some audit-request status validation errors */
  current_status?: string;
  /** Present on some 429 snapshot / rate-limit responses */
  retry_after_seconds?: number;
};

export * from './api-user-messages.en.js';

export function apiErrorJson(code: ApiErrorCode, error: string, details?: unknown): ApiErrorJsonBody {
  if (details === undefined) {
    return { code, error };
  }
  return { code, error, details };
}
