/**
 * Stable machine-readable `code` values for JSON error responses.
 * Human `error` strings stay English for logs/clients until a full i18n catalog ships.
 *
 * Inventory: docs/API_ERRORS_INVENTORY.md (literal messages) + this file (typed codes).
 */

import { COMPANY_URL_VALIDATION_EXAMPLE } from './api-validation-copy.js';

export const API_ERROR_CODES = {
  IDEMPOTENCY_PAYLOAD_MISMATCH: 'IDEMPOTENCY_PAYLOAD_MISMATCH',
  AUDIT_INITIALIZATION_FAILED: 'AUDIT_INITIALIZATION_FAILED',

  AUTH_MISSING_AUTHORIZATION: 'AUTH_MISSING_AUTHORIZATION',
  AUTH_INVALID_TOKEN: 'AUTH_INVALID_TOKEN',
  AUTH_AUTHENTICATION_FAILED: 'AUTH_AUTHENTICATION_FAILED',
  AUTH_NOT_AUTHENTICATED: 'AUTH_NOT_AUTHENTICATED',
  AUTH_PROFILE_LOAD_FAILED: 'AUTH_PROFILE_LOAD_FAILED',
  AUTH_PROFILE_CREATE_FAILED: 'AUTH_PROFILE_CREATE_FAILED',
  AUTH_PROFILE_UPDATE_FAILED: 'AUTH_PROFILE_UPDATE_FAILED',
  AUTH_PROFILE_LOOKUP_FAILED: 'AUTH_PROFILE_LOOKUP_FAILED',
  AUTH_ROLE_REQUIRED: 'AUTH_ROLE_REQUIRED',
  AUTH_GUEST_PORTAL_FORBIDDEN: 'AUTH_GUEST_PORTAL_FORBIDDEN',
  AUTH_REGISTERED_LOG_REQUIRED: 'AUTH_REGISTERED_LOG_REQUIRED',

  DISCOVER_ANSWERS_REQUIRED: 'DISCOVER_ANSWERS_REQUIRED',
  DISCOVER_MATURITY_INVALID: 'DISCOVER_MATURITY_INVALID',
  DISCOVER_FINDINGS_REQUIRED: 'DISCOVER_FINDINGS_REQUIRED',
  DISCOVER_SAVE_FAILED: 'DISCOVER_SAVE_FAILED',
  DISCOVER_UI_FRAGMENT_FAILED: 'DISCOVER_UI_FRAGMENT_FAILED',
  DISCOVER_ANALYTICS_PAYLOAD_INVALID: 'DISCOVER_ANALYTICS_PAYLOAD_INVALID',
  DISCOVER_ANALYTICS_STORE_FAILED: 'DISCOVER_ANALYTICS_STORE_FAILED',
  DISCOVER_ANALYTICS_ACCEPT_FAILED: 'DISCOVER_ANALYTICS_ACCEPT_FAILED',
  DISCOVER_LIST_FAILED: 'DISCOVER_LIST_FAILED',
  DISCOVER_INVALID_TOKEN: 'DISCOVER_INVALID_TOKEN',
  DISCOVER_SESSION_NOT_FOUND: 'DISCOVER_SESSION_NOT_FOUND',
  DISCOVER_LOAD_FAILED: 'DISCOVER_LOAD_FAILED',
  DISCOVER_CONTACT_EDIT_KEY_INVALID: 'DISCOVER_CONTACT_EDIT_KEY_INVALID',
  DISCOVER_CONTACT_FIELDS_REQUIRED: 'DISCOVER_CONTACT_FIELDS_REQUIRED',
  DISCOVER_CONTACT_EMPTY: 'DISCOVER_CONTACT_EMPTY',
  DISCOVER_CONTACT_SAVE_FAILED: 'DISCOVER_CONTACT_SAVE_FAILED',
  DISCOVER_CONTACT_NOT_ALLOWED: 'DISCOVER_CONTACT_NOT_ALLOWED',
  DISCOVER_CONVERT_FAILED: 'DISCOVER_CONVERT_FAILED',
  DISCOVER_ALREADY_CONVERTED: 'DISCOVER_ALREADY_CONVERTED',
  DISCOVER_FORBIDDEN_OWNER: 'DISCOVER_FORBIDDEN_OWNER',
  DISCOVER_CLAIM_CONFLICT: 'DISCOVER_CLAIM_CONFLICT',
  DISCOVER_LINK_CONFLICT: 'DISCOVER_LINK_CONFLICT',

  MARKETING_NAME_REQUIRED: 'MARKETING_NAME_REQUIRED',
  MARKETING_WEBSITE_OR_FLAG_REQUIRED: 'MARKETING_WEBSITE_OR_FLAG_REQUIRED',
  MARKETING_DEPTH_REQUIRED: 'MARKETING_DEPTH_REQUIRED',
  MARKETING_INVALID_RECOMMENDATION: 'MARKETING_INVALID_RECOMMENDATION',
  MARKETING_SAVE_FAILED: 'MARKETING_SAVE_FAILED',

  AUDITS_FORBIDDEN: 'AUDITS_FORBIDDEN',
  AUDITS_OMIT_COMPANY_URL_WHEN_NO_PUBLIC_WEBSITE: 'AUDITS_OMIT_COMPANY_URL_WHEN_NO_PUBLIC_WEBSITE',
  AUDITS_COMPANY_URL_REQUIRED: 'AUDITS_COMPANY_URL_REQUIRED',
  AUDITS_COMPANY_URL_INVALID: 'AUDITS_COMPANY_URL_INVALID',
  AUDITS_COMPANY_URL_NOT_ALLOWED: 'AUDITS_COMPANY_URL_NOT_ALLOWED',
  AUDITS_CREATE_FAILED: 'AUDITS_CREATE_FAILED',
  AUDITS_LIST_FAILED: 'AUDITS_LIST_FAILED',
  AUDITS_NOT_FOUND: 'AUDITS_NOT_FOUND',
  AUDITS_FETCH_FAILED: 'AUDITS_FETCH_FAILED',
  AUDITS_UPGRADE_PAYLOAD_INVALID: 'AUDITS_UPGRADE_PAYLOAD_INVALID',
  AUDITS_UPGRADE_FAILED: 'AUDITS_UPGRADE_FAILED',
  AUDITS_UPGRADE_NOT_FREE_SNAPSHOT: 'AUDITS_UPGRADE_NOT_FREE_SNAPSHOT',
  AUDITS_UPGRADE_NOT_COMPLETED: 'AUDITS_UPGRADE_NOT_COMPLETED',
  AUDITS_UPGRADE_ACCESS_DENIED: 'AUDITS_UPGRADE_ACCESS_DENIED',
  AUDITS_UPGRADE_RESET_DOMAINS_FAILED: 'AUDITS_UPGRADE_RESET_DOMAINS_FAILED',
  AUDITS_UPGRADE_INIT_DOMAINS_FAILED: 'AUDITS_UPGRADE_INIT_DOMAINS_FAILED',
  AUDITS_UPGRADE_INIT_REVIEWS_FAILED: 'AUDITS_UPGRADE_INIT_REVIEWS_FAILED',
  AUDITS_UPGRADE_INIT_STRATEGY_FAILED: 'AUDITS_UPGRADE_INIT_STRATEGY_FAILED',
  AUDITS_DELETE_FAILED: 'AUDITS_DELETE_FAILED',
  AUDITS_BRIEF_SCHEMA_FAILED: 'AUDITS_BRIEF_SCHEMA_FAILED',
  AUDITS_BRIEF_ANALYTICS_PAYLOAD_INVALID: 'AUDITS_BRIEF_ANALYTICS_PAYLOAD_INVALID',
  AUDITS_BRIEF_ANALYTICS_STORE_FAILED: 'AUDITS_BRIEF_ANALYTICS_STORE_FAILED',
  AUDITS_BRIEF_ANALYTICS_ACCEPT_FAILED: 'AUDITS_BRIEF_ANALYTICS_ACCEPT_FAILED',
  AUDITS_BRIEF_GET_FAILED: 'AUDITS_BRIEF_GET_FAILED',
  AUDITS_BRIEF_HELP_CLIENT_ONLY: 'AUDITS_BRIEF_HELP_CLIENT_ONLY',
  AUDITS_BRIEF_HELP_ACCESS_DENIED: 'AUDITS_BRIEF_HELP_ACCESS_DENIED',
  AUDITS_BRIEF_HELP_WRONG_PHASE: 'AUDITS_BRIEF_HELP_WRONG_PHASE',
  AUDITS_BRIEF_HELP_FAILED: 'AUDITS_BRIEF_HELP_FAILED',
  AUDITS_BRIEF_RESPONSES_NOT_OBJECT: 'AUDITS_BRIEF_RESPONSES_NOT_OBJECT',
  AUDITS_BRIEF_COLLECTION_MODE_INVALID: 'AUDITS_BRIEF_COLLECTION_MODE_INVALID',
  AUDITS_BRIEF_SAVE_FAILED: 'AUDITS_BRIEF_SAVE_FAILED',
  AUDITS_BRIEF_VALIDATION_FAILED: 'AUDITS_BRIEF_VALIDATION_FAILED',
  AUDITS_ACCESS_DENIED: 'AUDITS_ACCESS_DENIED',

  AUDIT_REQUEST_GUEST_FORBIDDEN: 'AUDIT_REQUEST_GUEST_FORBIDDEN',
  AUDIT_REQUEST_URL_OMIT_WHEN_NO_SITE: 'AUDIT_REQUEST_URL_OMIT_WHEN_NO_SITE',
  AUDIT_REQUEST_URL_OR_FLAG_REQUIRED: 'AUDIT_REQUEST_URL_OR_FLAG_REQUIRED',
  AUDIT_REQUEST_URL_NOT_ALLOWED: 'AUDIT_REQUEST_URL_NOT_ALLOWED',
  AUDIT_REQUEST_PRODUCT_MODE_INVALID: 'AUDIT_REQUEST_PRODUCT_MODE_INVALID',
  AUDIT_REQUEST_BRIEF_SNAPSHOT_INVALID: 'AUDIT_REQUEST_BRIEF_SNAPSHOT_INVALID',
  AUDIT_REQUEST_CREATE_FAILED: 'AUDIT_REQUEST_CREATE_FAILED',
  AUDIT_REQUEST_LIST_FAILED: 'AUDIT_REQUEST_LIST_FAILED',
  AUDIT_REQUEST_NOT_FOUND: 'AUDIT_REQUEST_NOT_FOUND',
  AUDIT_REQUEST_FETCH_FAILED: 'AUDIT_REQUEST_FETCH_FAILED',
  AUDIT_REQUEST_UPDATE_FAILED: 'AUDIT_REQUEST_UPDATE_FAILED',
  AUDIT_REQUEST_ACCESS_DENIED: 'AUDIT_REQUEST_ACCESS_DENIED',
  AUDIT_REQUEST_WRONG_STATUS_FOR_UPDATE: 'AUDIT_REQUEST_WRONG_STATUS_FOR_UPDATE',
  AUDIT_REQUEST_SUBMIT_MISSING_SITE: 'AUDIT_REQUEST_SUBMIT_MISSING_SITE',
  AUDIT_REQUEST_SUBMIT_NOT_DRAFT: 'AUDIT_REQUEST_SUBMIT_NOT_DRAFT',
  AUDIT_REQUEST_SUBMIT_FAILED: 'AUDIT_REQUEST_SUBMIT_FAILED',
  AUDIT_REQUEST_SUBMIT_WRONG_STATUS: 'AUDIT_REQUEST_SUBMIT_WRONG_STATUS',
  AUDIT_REQUEST_APPROVE_CLAIM_CONFLICT: 'AUDIT_REQUEST_APPROVE_CLAIM_CONFLICT',
  AUDIT_REQUEST_APPROVE_IN_PROGRESS: 'AUDIT_REQUEST_APPROVE_IN_PROGRESS',
  AUDIT_REQUEST_APPROVE_SEED_FAILED: 'AUDIT_REQUEST_APPROVE_SEED_FAILED',
  AUDIT_REQUEST_APPROVE_FAILED: 'AUDIT_REQUEST_APPROVE_FAILED',
  AUDIT_REQUEST_REJECT_WRONG_STATUS: 'AUDIT_REQUEST_REJECT_WRONG_STATUS',
  AUDIT_REQUEST_REJECT_FAILED: 'AUDIT_REQUEST_REJECT_FAILED',
  AUDIT_REQUEST_DELIVER_WRONG_STATUS: 'AUDIT_REQUEST_DELIVER_WRONG_STATUS',
  AUDIT_REQUEST_DELIVER_UPDATE_FAILED: 'AUDIT_REQUEST_DELIVER_UPDATE_FAILED',
  AUDIT_REQUEST_DELIVER_FAILED: 'AUDIT_REQUEST_DELIVER_FAILED',

  INCOMPLETE_INTAKE_VERSIONS: 'INCOMPLETE_INTAKE_VERSIONS',
  UNSUPPORTED_INTAKE_VERSION: 'UNSUPPORTED_INTAKE_VERSION',
  INTAKE_VERSION_CONFLICT: 'INTAKE_VERSION_CONFLICT',

  INTAKE_AUDIT_ID_FORMAT_INVALID: 'INTAKE_AUDIT_ID_FORMAT_INVALID',
  INTAKE_CREATE_LINK_FAILED: 'INTAKE_CREATE_LINK_FAILED',
  INTAKE_INVALID_TOKEN: 'INTAKE_INVALID_TOKEN',
  INTAKE_AUDIT_ID_REQUIRED: 'INTAKE_AUDIT_ID_REQUIRED',
  INTAKE_TOKEN_NOT_FOUND: 'INTAKE_TOKEN_NOT_FOUND',
  INTAKE_NOT_ALLOWED: 'INTAKE_NOT_ALLOWED',
  INTAKE_TOKEN_LINKED_CONFLICT: 'INTAKE_TOKEN_LINKED_CONFLICT',
  INTAKE_AUDIT_NOT_FOUND: 'INTAKE_AUDIT_NOT_FOUND',
  INTAKE_LINK_TOKEN_FAILED: 'INTAKE_LINK_TOKEN_FAILED',
  INTAKE_LINK_AUDIT_FAILED: 'INTAKE_LINK_AUDIT_FAILED',
  INTAKE_LIST_SUBMISSIONS_FAILED: 'INTAKE_LIST_SUBMISSIONS_FAILED',
  INTAKE_LINK_NOT_FOUND: 'INTAKE_LINK_NOT_FOUND',
  INTAKE_PRODUCT_MODE_INVALID: 'INTAKE_PRODUCT_MODE_INVALID',
  INTAKE_COLLECTION_MODE_INVALID: 'INTAKE_COLLECTION_MODE_INVALID',
  INTAKE_SURFACE_INVALID: 'INTAKE_SURFACE_INVALID',
  INTAKE_VERSION_TUPLE_UNSUPPORTED: 'INTAKE_VERSION_TUPLE_UNSUPPORTED',
  INTAKE_PLAN_TRACE_FAILED: 'INTAKE_PLAN_TRACE_FAILED',
  INTAKE_LINK_EXPIRED: 'INTAKE_LINK_EXPIRED',
  INTAKE_LOAD_FAILED: 'INTAKE_LOAD_FAILED',
  INTAKE_PREFILL_LOAD_FAILED: 'INTAKE_PREFILL_LOAD_FAILED',
  INTAKE_RESPONSES_REQUIRED: 'INTAKE_RESPONSES_REQUIRED',
  INTAKE_RESPONSES_SCHEMA_INVALID: 'INTAKE_RESPONSES_SCHEMA_INVALID',
  INTAKE_SAVE_RESPONSES_FAILED: 'INTAKE_SAVE_RESPONSES_FAILED',
  INTAKE_PREBRIEF_INCOMPLETE: 'INTAKE_PREBRIEF_INCOMPLETE',

  INTAKE_TRACE_ANALYTICS_PAYLOAD_INVALID: 'INTAKE_TRACE_ANALYTICS_PAYLOAD_INVALID',
  INTAKE_TRACE_ANALYTICS_STORE_FAILED: 'INTAKE_TRACE_ANALYTICS_STORE_FAILED',
  INTAKE_TRACE_ANALYTICS_ACCEPT_FAILED: 'INTAKE_TRACE_ANALYTICS_ACCEPT_FAILED',
  INTAKE_TRACE_WORDING_LOAD_FAILED: 'INTAKE_TRACE_WORDING_LOAD_FAILED',
  INTAKE_TRACE_WORDING_PAYLOAD_INVALID: 'INTAKE_TRACE_WORDING_PAYLOAD_INVALID',
  INTAKE_TRACE_WORDING_UPDATE_FAILED: 'INTAKE_TRACE_WORDING_UPDATE_FAILED',
  INTAKE_TRACE_WORDING_SAVE_FAILED: 'INTAKE_TRACE_WORDING_SAVE_FAILED',
  INTAKE_TRACE_PUBLISH_PAYLOAD_INVALID: 'INTAKE_TRACE_PUBLISH_PAYLOAD_INVALID',
  INTAKE_TRACE_PUBLISH_FAILED: 'INTAKE_TRACE_PUBLISH_FAILED',
  INTAKE_TRACE_ROLLBACK_PAYLOAD_INVALID: 'INTAKE_TRACE_ROLLBACK_PAYLOAD_INVALID',
  INTAKE_TRACE_ROLLBACK_FAILED: 'INTAKE_TRACE_ROLLBACK_FAILED',
  INTAKE_TRACE_PUBLICATION_LOG_QUERY_INVALID: 'INTAKE_TRACE_PUBLICATION_LOG_QUERY_INVALID',
  INTAKE_TRACE_PUBLICATION_LOG_FAILED: 'INTAKE_TRACE_PUBLICATION_LOG_FAILED',

  NOTIFICATIONS_LIST_FAILED: 'NOTIFICATIONS_LIST_FAILED',
  NOTIFICATIONS_UNREAD_COUNT_FAILED: 'NOTIFICATIONS_UNREAD_COUNT_FAILED',
  NOTIFICATIONS_NOT_FOUND: 'NOTIFICATIONS_NOT_FOUND',
  NOTIFICATIONS_MARK_READ_FAILED: 'NOTIFICATIONS_MARK_READ_FAILED',
  NOTIFICATIONS_MARK_ALL_FAILED: 'NOTIFICATIONS_MARK_ALL_FAILED',

  PLATFORM_SELF_SERVE_LOAD_FAILED: 'PLATFORM_SELF_SERVE_LOAD_FAILED',
  PLATFORM_ADMIN_ONLY: 'PLATFORM_ADMIN_ONLY',
  PLATFORM_OWNER_REQUIRED: 'PLATFORM_OWNER_REQUIRED',
  PLATFORM_OWNER_UUID_INVALID: 'PLATFORM_OWNER_UUID_INVALID',
  PLATFORM_OWNER_NOT_CONSULTANT: 'PLATFORM_OWNER_NOT_CONSULTANT',
  PLATFORM_SELF_SERVE_PERSIST_FAILED: 'PLATFORM_SELF_SERVE_PERSIST_FAILED',
  PLATFORM_SELF_SERVE_UPDATE_FAILED: 'PLATFORM_SELF_SERVE_UPDATE_FAILED',
  PLATFORM_CONSULTANT_ALLOWLIST_LOAD_FAILED: 'PLATFORM_CONSULTANT_ALLOWLIST_LOAD_FAILED',
  PLATFORM_CONSULTANT_ALLOWLIST_EMAIL_INVALID: 'PLATFORM_CONSULTANT_ALLOWLIST_EMAIL_INVALID',
  PLATFORM_CONSULTANT_ALLOWLIST_ADD_FAILED: 'PLATFORM_CONSULTANT_ALLOWLIST_ADD_FAILED',
  PLATFORM_CONSULTANT_ALLOWLIST_REMOVE_FAILED: 'PLATFORM_CONSULTANT_ALLOWLIST_REMOVE_FAILED',

  PROFILE_LOAD_FAILED: 'PROFILE_LOAD_FAILED',
  PROFILE_PAYLOAD_INVALID: 'PROFILE_PAYLOAD_INVALID',
  PROFILE_UPDATE_FAILED: 'PROFILE_UPDATE_FAILED',

  REPORTS_AUDIT_NOT_FOUND: 'REPORTS_AUDIT_NOT_FOUND',
  REPORTS_GENERATE_FAILED: 'REPORTS_GENERATE_FAILED',

  SELF_SERVE_OWNER_UNAVAILABLE: 'SELF_SERVE_OWNER_UNAVAILABLE',

  SNAPSHOT_QUOTA_READ_FAILED: 'SNAPSHOT_QUOTA_READ_FAILED',
  SNAPSHOT_TOKEN_REQUIRED: 'SNAPSHOT_TOKEN_REQUIRED',
  SNAPSHOT_NOT_FOUND: 'SNAPSHOT_NOT_FOUND',
  SNAPSHOT_TOKEN_EXPIRED: 'SNAPSHOT_TOKEN_EXPIRED',
  SNAPSHOT_CLAIM_FAILED: 'SNAPSHOT_CLAIM_FAILED',
  SNAPSHOT_COMPANY_URL_REQUIRED: 'SNAPSHOT_COMPANY_URL_REQUIRED',
  SNAPSHOT_CREATE_FAILED: 'SNAPSHOT_CREATE_FAILED',
  SNAPSHOT_INIT_ROLLBACK: 'SNAPSHOT_INIT_ROLLBACK',
  SNAPSHOT_START_FAILED: 'SNAPSHOT_START_FAILED',
  SNAPSHOT_RESOURCE_NOT_FOUND: 'SNAPSHOT_RESOURCE_NOT_FOUND',
  SNAPSHOT_METRICS_FAILED: 'SNAPSHOT_METRICS_FAILED',
  SNAPSHOT_HOST_REQUIRED: 'SNAPSHOT_HOST_REQUIRED',
  SNAPSHOT_PURGE_FAILED: 'SNAPSHOT_PURGE_FAILED',
  SNAPSHOT_INVALID_TOKEN: 'SNAPSHOT_INVALID_TOKEN',
  SNAPSHOT_FETCH_FAILED: 'SNAPSHOT_FETCH_FAILED',
  /** Claim would overwrite another user's attachment */
  SNAPSHOT_CLAIM_CONFLICT: 'SNAPSHOT_CLAIM_CONFLICT',
  /** PublicUrlNotAllowedError — same machine code as historical clients expect */
  SNAPSHOT_INVALID_COMPANY_URL: 'INVALID_COMPANY_URL',
  /** Per-domain fresh-scan cooldown for free tool */
  SNAPSHOT_DOMAIN_FRESH_COOLDOWN: 'DOMAIN_FRESH_COOLDOWN',

  PIPELINE_FORBIDDEN: 'PIPELINE_FORBIDDEN',
  PIPELINE_AUDIT_NOT_FOUND: 'PIPELINE_AUDIT_NOT_FOUND',
  PIPELINE_ACCESS_DENIED: 'PIPELINE_ACCESS_DENIED',
  PIPELINE_ALREADY_STARTED: 'PIPELINE_ALREADY_STARTED',
  PIPELINE_TOKEN_BUDGET_EXCEEDED: 'PIPELINE_TOKEN_BUDGET_EXCEEDED',
  PIPELINE_START_CLAIM_CONFLICT: 'PIPELINE_START_CLAIM_CONFLICT',
  PIPELINE_PHASE_IN_PROGRESS: 'PIPELINE_PHASE_IN_PROGRESS',
  PIPELINE_ALL_PHASES_COMPLETE: 'PIPELINE_ALL_PHASES_COMPLETE',
  PIPELINE_REVIEW_PENDING: 'PIPELINE_REVIEW_PENDING',
  PIPELINE_NEXT_CLAIM_CONFLICT: 'PIPELINE_NEXT_CLAIM_CONFLICT',
  PIPELINE_PHASE_REQUIRED: 'PIPELINE_PHASE_REQUIRED',
  PIPELINE_PHASE_OUT_OF_RANGE: 'PIPELINE_PHASE_OUT_OF_RANGE',
  PIPELINE_PHASE_NOT_AVAILABLE_FOR_MODE: 'PIPELINE_PHASE_NOT_AVAILABLE_FOR_MODE',
  PIPELINE_RETRY_CLAIM_CONFLICT: 'PIPELINE_RETRY_CLAIM_CONFLICT',
  PIPELINE_STATUS_FAILED: 'PIPELINE_STATUS_FAILED',
  PIPELINE_QUALITY_GATE_FETCH_FAILED: 'PIPELINE_QUALITY_GATE_FETCH_FAILED',
  PIPELINE_REVIEW_APPROVE_FAILED: 'PIPELINE_REVIEW_APPROVE_FAILED',
  PIPELINE_QUALITY_GATE_REQUIRES_NOTES: 'PIPELINE_QUALITY_GATE_REQUIRES_NOTES',
  PIPELINE_START_FAILED: 'PIPELINE_START_FAILED',
  PIPELINE_NEXT_FAILED: 'PIPELINE_NEXT_FAILED',
  PIPELINE_RETRY_FAILED: 'PIPELINE_RETRY_FAILED',
} as const;

export type ApiErrorCode = (typeof API_ERROR_CODES)[keyof typeof API_ERROR_CODES];

export type ApiErrorJsonBody = {
  code: ApiErrorCode;
  error: string;
  details?: unknown;
  /** Present on some 409 discovery responses */
  audit_id?: string | null;
  /** Present on some audit-request status validation errors */
  current_status?: string;
  /** Present on some 429 snapshot / rate-limit responses */
  retry_after_seconds?: number;
};

/** User-safe message for idempotency key reused with a different body (no internal details). */
export const IDEMPOTENCY_PAYLOAD_MISMATCH_MESSAGE =
  'This idempotency key was already used with a different request body.';

/** Generic create failure after rollback (details only in server logs). */
export const AUDIT_INITIALIZATION_FAILED_MESSAGE = 'Failed to create audit';

export const AUTH_MISSING_AUTHORIZATION_MESSAGE = 'Missing or invalid Authorization header';
export const AUTH_INVALID_TOKEN_MESSAGE = 'Invalid or expired token';
export const AUTH_AUTHENTICATION_FAILED_MESSAGE = 'Authentication failed';
export const AUTH_NOT_AUTHENTICATED_MESSAGE = 'Not authenticated';
export const AUTH_PROFILE_LOAD_FAILED_MESSAGE = 'Failed to load user profile';
export const AUTH_PROFILE_CREATE_FAILED_MESSAGE = 'Failed to create user profile';
export const AUTH_PROFILE_UPDATE_FAILED_MESSAGE = 'Failed to update user profile';
export const AUTH_PROFILE_LOOKUP_FAILED_MESSAGE = 'Profile lookup failed';
export const AUTH_GUEST_PORTAL_FORBIDDEN_MESSAGE =
  'Complete registration to access this in the portal.';
export const AUTH_REGISTERED_LOG_REQUIRED_MESSAGE = 'Use POST /api/log for registered accounts.';

export function authRoleRequiredMessage(role: string): string {
  return `Access denied. Required role: ${role}`;
}

export const DISCOVER_ANSWERS_REQUIRED_MESSAGE = 'answers object is required';
export const DISCOVER_MATURITY_INVALID_MESSAGE = 'maturity_level must be an integer 1–5';
export const DISCOVER_FINDINGS_REQUIRED_MESSAGE = 'findings must be an array';
export const DISCOVER_SAVE_FAILED_MESSAGE = 'Failed to save discovery session';
export const DISCOVER_UI_FRAGMENT_FAILED_MESSAGE = 'Failed to build discovery UI fragment';
export const DISCOVER_ANALYTICS_PAYLOAD_INVALID_MESSAGE = 'Invalid analytics payload';
export const DISCOVER_ANALYTICS_STORE_FAILED_MESSAGE = 'Failed to store analytics events';
export const DISCOVER_ANALYTICS_ACCEPT_FAILED_MESSAGE = 'Failed to accept analytics events';
export const DISCOVER_LIST_FAILED_MESSAGE = 'Failed to list sessions';
export const DISCOVER_INVALID_TOKEN_MESSAGE = 'Invalid token';
export const DISCOVER_SESSION_NOT_FOUND_MESSAGE = 'Session not found';
export const DISCOVER_LOAD_FAILED_MESSAGE = 'Failed to load session';
export const DISCOVER_CONTACT_EDIT_KEY_INVALID_MESSAGE = 'Invalid or missing contact edit key';
export const DISCOVER_CONTACT_FIELDS_REQUIRED_MESSAGE =
  'Provide at least one of contact_name, contact_email, contact_phone, contact_company';
export const DISCOVER_CONTACT_EMPTY_MESSAGE = 'At least one contact field must be non-empty';
export const DISCOVER_CONTACT_SAVE_FAILED_MESSAGE = 'Failed to save contact info';
export const DISCOVER_CONTACT_NOT_ALLOWED_MESSAGE = 'Contact update not allowed for this session';
export const DISCOVER_CONVERT_FAILED_MESSAGE = 'Failed to convert session';
export const DISCOVER_ALREADY_CONVERTED_MESSAGE = 'Session already converted';
export const DISCOVER_FORBIDDEN_OWNER_MESSAGE = 'Session is assigned to another consultant';
export const DISCOVER_CLAIM_CONFLICT_MESSAGE = 'Session was claimed or converted by another request';
export const DISCOVER_LINK_CONFLICT_MESSAGE = 'Session conversion conflict. Please retry.';

export const MARKETING_NAME_REQUIRED_MESSAGE = 'Name is required';
export const MARKETING_WEBSITE_OR_FLAG_REQUIRED_MESSAGE =
  'Provide a website URL or mark no website';
export const MARKETING_DEPTH_REQUIRED_MESSAGE =
  'preferred_audit_depth is required (express or full) when you have a site and are sure about the format';
export const MARKETING_INVALID_RECOMMENDATION_MESSAGE = 'Invalid recommendation';
export const MARKETING_SAVE_FAILED_MESSAGE = 'Failed to save brief';

export const AUDITS_FORBIDDEN_MESSAGE = 'Forbidden';
export const AUDITS_OMIT_COMPANY_URL_WHEN_NO_PUBLIC_WEBSITE_MESSAGE =
  'Omit company_url when no_public_website is true';
export const AUDITS_COMPANY_URL_REQUIRED_MESSAGE = 'company_url is required';
export const AUDITS_COMPANY_URL_INVALID_MESSAGE = `company_url must be a valid URL (e.g. ${COMPANY_URL_VALIDATION_EXAMPLE})`;
export const AUDITS_COMPANY_URL_NOT_ALLOWED_MESSAGE = 'company_url is not allowed';
export const AUDITS_CREATE_FAILED_MESSAGE = 'Failed to create audit';
export const AUDITS_LIST_FAILED_MESSAGE = 'Failed to list audits';
export const AUDITS_NOT_FOUND_MESSAGE = 'Audit not found';
export const AUDITS_FETCH_FAILED_MESSAGE = 'Failed to fetch audit';
export const AUDITS_UPGRADE_PAYLOAD_INVALID_MESSAGE =
  'Invalid payload — need target_mode and use_scraped_context';
export const AUDITS_UPGRADE_FAILED_MESSAGE = 'Upgrade failed';
export const AUDITS_UPGRADE_NOT_FREE_SNAPSHOT_MESSAGE = 'Only free snapshot audits can use this upgrade';
export const AUDITS_UPGRADE_NOT_COMPLETED_MESSAGE = 'Snapshot must be completed before upgrading';
export const AUDITS_UPGRADE_ACCESS_DENIED_MESSAGE = 'Access denied';
export const AUDITS_UPGRADE_RESET_DOMAINS_FAILED_MESSAGE = 'Failed to reset audit domains';
export const AUDITS_UPGRADE_INIT_DOMAINS_FAILED_MESSAGE = 'Failed to initialize audit domains';
export const AUDITS_UPGRADE_INIT_REVIEWS_FAILED_MESSAGE = 'Failed to initialize review points';
export const AUDITS_UPGRADE_INIT_STRATEGY_FAILED_MESSAGE = 'Failed to initialize strategy placeholder';
export const AUDITS_DELETE_FAILED_MESSAGE = 'Failed to delete audit';
export const AUDITS_BRIEF_SCHEMA_FAILED_MESSAGE = 'Failed to get brief schema';
export const AUDITS_BRIEF_ANALYTICS_PAYLOAD_INVALID_MESSAGE = 'Invalid analytics payload';
export const AUDITS_BRIEF_ANALYTICS_STORE_FAILED_MESSAGE = 'Failed to store analytics events';
export const AUDITS_BRIEF_ANALYTICS_ACCEPT_FAILED_MESSAGE = 'Failed to accept analytics events';
export const AUDITS_BRIEF_GET_FAILED_MESSAGE = 'Failed to get brief';
export const AUDITS_BRIEF_HELP_CLIENT_ONLY_MESSAGE =
  'Only clients can request brief help from this endpoint';
export const AUDITS_BRIEF_HELP_ACCESS_DENIED_MESSAGE = 'Access denied';
export const AUDITS_BRIEF_HELP_WRONG_PHASE_MESSAGE =
  'Help request is only available before the pipeline has started';
export const AUDITS_BRIEF_HELP_FAILED_MESSAGE = 'Failed to record help request';
export const AUDITS_BRIEF_RESPONSES_NOT_OBJECT_MESSAGE = 'responses must be an object';
export const AUDITS_BRIEF_COLLECTION_MODE_INVALID_MESSAGE = 'Invalid collection_mode';
export const AUDITS_BRIEF_SAVE_FAILED_MESSAGE = 'Failed to save brief';
export const AUDITS_ACCESS_DENIED_MESSAGE = 'Access denied';

export const AUDIT_REQUEST_GUEST_FORBIDDEN_MESSAGE =
  'Complete registration (email or Google) to use the client portal.';
export const AUDIT_REQUEST_URL_OMIT_WHEN_NO_SITE_MESSAGE =
  'Leave the website field empty when you have no public website.';
export const AUDIT_REQUEST_URL_OR_FLAG_REQUIRED_MESSAGE =
  'Enter your website URL, or indicate that you have no public website.';
export const AUDIT_REQUEST_URL_NOT_ALLOWED_MESSAGE = 'url is not allowed';
export const AUDIT_REQUEST_PRODUCT_MODE_INVALID_MESSAGE = 'product_mode must be "express" or "full"';
export const AUDIT_REQUEST_CREATE_FAILED_MESSAGE = 'Failed to create audit request';
export const AUDIT_REQUEST_LIST_FAILED_MESSAGE = 'Failed to list audit requests';
export const AUDIT_REQUEST_NOT_FOUND_MESSAGE = 'Audit request not found';
export const AUDIT_REQUEST_FETCH_FAILED_MESSAGE = 'Failed to fetch audit request';
export const AUDIT_REQUEST_UPDATE_FAILED_MESSAGE = 'Failed to update audit request';
export const AUDIT_REQUEST_ACCESS_DENIED_MESSAGE = 'Access denied';
export const AUDIT_REQUEST_WRONG_STATUS_FOR_UPDATE_MESSAGE =
  'Only draft or submitted requests can be updated';
export const AUDIT_REQUEST_SUBMIT_MISSING_SITE_MESSAGE =
  'Request is missing a valid website or no-public-website flag.';
export const AUDIT_REQUEST_SUBMIT_NOT_DRAFT_MESSAGE = 'Only draft requests can be submitted';
export const AUDIT_REQUEST_SUBMIT_FAILED_MESSAGE = 'Failed to submit audit request';
export const AUDIT_REQUEST_SUBMIT_WRONG_STATUS_MESSAGE =
  'Request must be submitted or under review to approve';
export const AUDIT_REQUEST_APPROVE_CLAIM_CONFLICT_MESSAGE =
  'Approve request already claimed by another request';
export const AUDIT_REQUEST_APPROVE_IN_PROGRESS_MESSAGE = 'Approve request is already in progress';
export const AUDIT_REQUEST_APPROVE_SEED_FAILED_MESSAGE = 'Failed to seed intake brief from request';
export const AUDIT_REQUEST_APPROVE_FAILED_MESSAGE = 'Failed to approve audit request';
export const AUDIT_REQUEST_REJECT_WRONG_STATUS_MESSAGE =
  'Only submitted/under_review requests can be rejected';
export const AUDIT_REQUEST_REJECT_FAILED_MESSAGE = 'Failed to reject audit request';
export const AUDIT_REQUEST_DELIVER_WRONG_STATUS_MESSAGE =
  'Only approved or running requests can be marked as delivered';
export const AUDIT_REQUEST_DELIVER_UPDATE_FAILED_MESSAGE = 'Failed to update request';
export const AUDIT_REQUEST_DELIVER_FAILED_MESSAGE = 'Failed to mark as delivered';

export const INCOMPLETE_INTAKE_VERSIONS_MESSAGE =
  'intake_versions must include all of questionBankVersion, policyVersion, layoutVersion, resolverVersion, or be omitted.';
export const UNSUPPORTED_INTAKE_VERSION_MESSAGE =
  'intake_versions tuple is not a supported artifact bundle';
export const INTAKE_VERSION_CONFLICT_MESSAGE =
  'intake_versions does not match this brief row; refresh the brief or send the stored tuple.';

export const INTAKE_AUDIT_ID_FORMAT_INVALID_MESSAGE = 'audit_id must be a string UUID when provided';
export const INTAKE_CREATE_LINK_FAILED_MESSAGE = 'Failed to create intake link';
export const INTAKE_INVALID_TOKEN_MESSAGE = 'Invalid token';
export const INTAKE_AUDIT_ID_REQUIRED_MESSAGE = 'audit_id is required';
export const INTAKE_TOKEN_NOT_FOUND_MESSAGE = 'Token not found';
export const INTAKE_NOT_ALLOWED_MESSAGE = 'Not allowed';
export const INTAKE_TOKEN_LINKED_CONFLICT_MESSAGE = 'This link is already linked to another audit';
export const INTAKE_AUDIT_NOT_FOUND_MESSAGE = 'Audit not found';
export const INTAKE_LINK_TOKEN_FAILED_MESSAGE = 'Failed to link token';
export const INTAKE_LINK_AUDIT_FAILED_MESSAGE = 'Failed to link intake token';
export const INTAKE_LIST_SUBMISSIONS_FAILED_MESSAGE = 'Failed to list submissions';
export const INTAKE_LINK_NOT_FOUND_MESSAGE = 'Link not found';
export const INTAKE_LINK_EXPIRED_MESSAGE = 'This link has expired';
export const INTAKE_LOAD_FAILED_MESSAGE = 'Failed to load intake link';
export const INTAKE_PREFILL_LOAD_FAILED_MESSAGE = 'Failed to load intake prefill';
export const INTAKE_RESPONSES_REQUIRED_MESSAGE = 'responses object is required';
export const INTAKE_SAVE_RESPONSES_FAILED_MESSAGE = 'Failed to save responses';
export const INTAKE_PREBRIEF_INCOMPLETE_MESSAGE =
  'Pre-brief incomplete. If you selected Other for industry, describe your sector in the follow-up field.';

export function intakeProductModeInvalidMessage(rawMode: string, validList: string): string {
  return `Invalid productMode "${rawMode}". Valid values: ${validList}`;
}

export const INTAKE_VERSION_TUPLE_UNSUPPORTED_MESSAGE =
  'Unsupported intakeVersionTuple — not current and not in frozen registry.';
export const INTAKE_PLAN_TRACE_FAILED_MESSAGE = 'Failed to build intake plan trace';

export function intakeResponsesSchemaInvalidMessage(zodMessage: string): string {
  return `Invalid responses: ${zodMessage}`;
}

export const INTAKE_TRACE_ANALYTICS_PAYLOAD_INVALID_MESSAGE = 'Invalid analytics payload';
export const INTAKE_TRACE_ANALYTICS_STORE_FAILED_MESSAGE = 'Failed to store analytics events';
export const INTAKE_TRACE_ANALYTICS_ACCEPT_FAILED_MESSAGE = 'Failed to accept analytics events';
export const INTAKE_TRACE_WORDING_LOAD_FAILED_MESSAGE = 'Failed to load wording drafts';
export const INTAKE_TRACE_WORDING_PAYLOAD_INVALID_MESSAGE = 'Invalid wording drafts payload';
export const INTAKE_TRACE_WORDING_UPDATE_FAILED_MESSAGE = 'Failed to update wording drafts';
export const INTAKE_TRACE_WORDING_SAVE_FAILED_MESSAGE = 'Failed to save wording drafts';
export const INTAKE_TRACE_PUBLISH_PAYLOAD_INVALID_MESSAGE = 'Invalid publish payload';
export const INTAKE_TRACE_PUBLISH_FAILED_MESSAGE = 'Failed to publish wording';
export const INTAKE_TRACE_ROLLBACK_PAYLOAD_INVALID_MESSAGE = 'Invalid rollback payload';
export const INTAKE_TRACE_ROLLBACK_FAILED_MESSAGE = 'Failed to rollback wording';
export const INTAKE_TRACE_PUBLICATION_LOG_QUERY_INVALID_MESSAGE = 'Invalid query';
export const INTAKE_TRACE_PUBLICATION_LOG_FAILED_MESSAGE = 'Failed to load publication log';

export const NOTIFICATIONS_LIST_FAILED_MESSAGE = 'Failed to list notifications';
export const NOTIFICATIONS_UNREAD_COUNT_FAILED_MESSAGE = 'Failed to fetch unread count';
export const NOTIFICATIONS_NOT_FOUND_MESSAGE = 'Notification not found';
export const NOTIFICATIONS_MARK_READ_FAILED_MESSAGE = 'Failed to mark notification as read';
export const NOTIFICATIONS_MARK_ALL_FAILED_MESSAGE = 'Failed to mark all notifications as read';

export const PLATFORM_SELF_SERVE_LOAD_FAILED_MESSAGE = 'Failed to load platform settings';
export const PLATFORM_ADMIN_ONLY_MESSAGE = 'Only platform administrators can change this setting';
export const PLATFORM_OWNER_REQUIRED_MESSAGE = 'owner_user_id is required (UUID string or null)';
export const PLATFORM_OWNER_UUID_INVALID_MESSAGE = 'owner_user_id must be a string UUID or null';
export const PLATFORM_OWNER_NOT_CONSULTANT_MESSAGE =
  'owner_user_id must be an active consultant profile';
export const PLATFORM_SELF_SERVE_PERSIST_FAILED_MESSAGE = 'Failed to update platform settings';
export const PLATFORM_SELF_SERVE_UPDATE_FAILED_MESSAGE = 'Failed to update platform settings';
export const PLATFORM_CONSULTANT_ALLOWLIST_LOAD_FAILED_MESSAGE = 'Failed to load consultant email allowlist';
export const PLATFORM_CONSULTANT_ALLOWLIST_EMAIL_INVALID_MESSAGE = 'Invalid email for allowlist';
export const PLATFORM_CONSULTANT_ALLOWLIST_ADD_FAILED_MESSAGE = 'Failed to add email to allowlist';
export const PLATFORM_CONSULTANT_ALLOWLIST_REMOVE_FAILED_MESSAGE = 'Failed to remove email from allowlist';

export const PROFILE_LOAD_FAILED_MESSAGE = 'Failed to load user profile';
export const PROFILE_PAYLOAD_INVALID_MESSAGE = 'Invalid profile payload';
export const PROFILE_UPDATE_FAILED_MESSAGE = 'Failed to update user profile';

export const REPORTS_AUDIT_NOT_FOUND_MESSAGE = 'Audit not found';
export const REPORTS_GENERATE_FAILED_MESSAGE = 'Failed to generate report';

export const SELF_SERVE_OWNER_UNAVAILABLE_MESSAGE =
  'This feature is temporarily unavailable. Please try again in a few minutes.';

export const SNAPSHOT_QUOTA_READ_FAILED_MESSAGE = 'Failed to read quota';
export const SNAPSHOT_TOKEN_REQUIRED_MESSAGE = 'snapshot_token is required';
export const SNAPSHOT_NOT_FOUND_MESSAGE = 'Snapshot not found';
export const SNAPSHOT_TOKEN_EXPIRED_MESSAGE = 'Snapshot token expired';
export const SNAPSHOT_CLAIM_FAILED_MESSAGE = 'Failed to claim snapshot';
export const SNAPSHOT_COMPANY_URL_REQUIRED_MESSAGE = 'company_url is required';
export const SNAPSHOT_CREATE_FAILED_MESSAGE = 'Failed to create snapshot';
export const SNAPSHOT_INIT_ROLLBACK_MESSAGE = 'Failed to initialize snapshot — rolled back';
export const SNAPSHOT_START_FAILED_MESSAGE = 'Failed to start snapshot';
export const SNAPSHOT_RESOURCE_NOT_FOUND_MESSAGE = 'Not found';
export const SNAPSHOT_METRICS_FAILED_MESSAGE = 'Metrics failed';
export const SNAPSHOT_HOST_REQUIRED_MESSAGE = 'host is required';
export const SNAPSHOT_PURGE_FAILED_MESSAGE = 'Purge failed';
export const SNAPSHOT_INVALID_TOKEN_MESSAGE = 'Invalid snapshot token';
export const SNAPSHOT_FETCH_FAILED_MESSAGE = 'Failed to fetch snapshot';
export const SNAPSHOT_CLAIM_CONFLICT_MESSAGE = 'This snapshot cannot be saved to your account.';
export const SNAPSHOT_DOMAIN_FRESH_COOLDOWN_MESSAGE =
  'This website was just scanned from our free tool. Please wait a few minutes before starting another fresh check for the same site.';

export function snapshotCompanyUrlNotAllowedMessage(detail: string): string {
  const t = detail.trim();
  return t ? `company_url is not allowed: ${t}` : 'company_url is not allowed';
}

export const PIPELINE_FORBIDDEN_MESSAGE = 'Forbidden';
export const PIPELINE_AUDIT_NOT_FOUND_MESSAGE = 'Audit not found';
export const PIPELINE_ACCESS_DENIED_MESSAGE = 'Access denied';
export const PIPELINE_ALREADY_STARTED_MESSAGE = 'Pipeline already started';
export const PIPELINE_TOKEN_BUDGET_EXCEEDED_MESSAGE = 'Token budget exceeded';
export const PIPELINE_START_CLAIM_CONFLICT_MESSAGE =
  'Pipeline start already claimed by another request';
export const PIPELINE_PHASE_IN_PROGRESS_MESSAGE = 'A phase is already in progress';
export const PIPELINE_ALL_PHASES_COMPLETE_MESSAGE = 'All phases completed';
export const PIPELINE_REVIEW_PENDING_MESSAGE = 'Review point pending';
export const PIPELINE_NEXT_CLAIM_CONFLICT_MESSAGE =
  'Next phase request already claimed by another request';
export const PIPELINE_RETRY_CLAIM_CONFLICT_MESSAGE =
  'Retry request already claimed by another request';
export const PIPELINE_PHASE_REQUIRED_MESSAGE = 'phase is required (number)';
export const PIPELINE_STATUS_FAILED_MESSAGE = 'Failed to get pipeline status';
export const PIPELINE_QUALITY_GATE_FETCH_FAILED_MESSAGE = 'Failed to fetch quality gate report';
export const PIPELINE_REVIEW_APPROVE_FAILED_MESSAGE = 'Failed to approve review';
export const PIPELINE_QUALITY_GATE_REQUIRES_NOTES_MESSAGE = 'quality_gate_requires_notes';
export const PIPELINE_START_FAILED_MESSAGE = 'Failed to start pipeline';
export const PIPELINE_NEXT_FAILED_MESSAGE = 'Failed to run next phase';
export const PIPELINE_RETRY_FAILED_MESSAGE = 'Failed to retry phase';

export function pipelinePhaseOutOfRangeMessage(min: number, max: number): string {
  return `phase must be an integer between ${min} and ${max}`;
}

export function pipelinePhaseNotAvailableMessage(phase: number, mode: string): string {
  return `Phase ${phase} is not available for product_mode '${mode}'`;
}

export function apiErrorJson(code: ApiErrorCode, error: string, details?: unknown): ApiErrorJsonBody {
  if (details === undefined) {
    return { code, error };
  }
  return { code, error, details };
}
