import { DIRECTOR_SUB_AGENT_IDS, type DirectorSubAgentId } from './director-sub-agents.js';

export const DIRECTOR_OPERATING_MODES = [
  'discovery',
  'launch',
  'growth',
  'authority',
  'defense',
] as const;

export type DirectorOperatingMode = (typeof DIRECTOR_OPERATING_MODES)[number];

const D = 'deferred' as const;
type Depth = 'min' | 'standard' | 'max' | 'deferred';

function buildDeferredDepthMap(): Record<DirectorSubAgentId, Depth> {
  return Object.fromEntries(DIRECTOR_SUB_AGENT_IDS.map(id => [id, D])) as Record<DirectorSubAgentId, Depth>;
}

const BASE_DEFERRED_DEPTHS = buildDeferredDepthMap();

/**
 * Per-mode depth. Agents 1,2,4,6,7,8,10,11,12 are **deferred in every mode** so default
 * auto-runs still match 3/5/9 token policy; explicit `sub_agent_ids` can request them.
 */
export const DIRECTOR_MODE_AGENT_DEPTHS: Record<DirectorOperatingMode, Record<DirectorSubAgentId, Depth>> = {
  discovery: {
    ...BASE_DEFERRED_DEPTHS,
    'cmo.agent_1_market': D,
    'cmo.agent_2_awareness_ladder': D,
    'cmo.agent_3_positioning': 'max',
    'cmo.agent_4_voice': D,
    'cmo.agent_5_content_strategy': 'standard',
    'cmo.agent_6_viral': D,
    'cmo.agent_7_storytelling': D,
    'cmo.agent_8_ready_posts': D,
    'cmo.agent_9_traffic': 'min',
    'cmo.agent_10_distribution': D,
    'cmo.agent_11_founder_brand': D,
    'cmo.agent_12_growth_loops': D,
    'cdo.funnel_architect': D,
    'cdo.friction': D,
    'cdo.experimentation': D,
    'cao.process_map': D,
    'cao.automation_candidates': D,
    'cao.throughput': D,
    'cso.case_classifier': D,
    'cso.threat_model': D,
    'cso.compliance_map': D,
  },
  launch: {
    ...BASE_DEFERRED_DEPTHS,
    'cmo.agent_1_market': D,
    'cmo.agent_2_awareness_ladder': D,
    'cmo.agent_3_positioning': 'standard',
    'cmo.agent_4_voice': D,
    'cmo.agent_5_content_strategy': 'max',
    'cmo.agent_6_viral': D,
    'cmo.agent_7_storytelling': D,
    'cmo.agent_8_ready_posts': D,
    'cmo.agent_9_traffic': 'standard',
    'cmo.agent_10_distribution': D,
    'cmo.agent_11_founder_brand': D,
    'cmo.agent_12_growth_loops': D,
    'cdo.funnel_architect': D,
    'cdo.friction': D,
    'cdo.experimentation': D,
    'cao.process_map': D,
    'cao.automation_candidates': D,
    'cao.throughput': D,
    'cso.case_classifier': D,
    'cso.threat_model': D,
    'cso.compliance_map': D,
  },
  growth: {
    ...BASE_DEFERRED_DEPTHS,
    'cmo.agent_1_market': D,
    'cmo.agent_2_awareness_ladder': D,
    'cmo.agent_3_positioning': 'standard',
    'cmo.agent_4_voice': D,
    'cmo.agent_5_content_strategy': 'standard',
    'cmo.agent_6_viral': D,
    'cmo.agent_7_storytelling': D,
    'cmo.agent_8_ready_posts': D,
    'cmo.agent_9_traffic': 'max',
    'cmo.agent_10_distribution': D,
    'cmo.agent_11_founder_brand': D,
    'cmo.agent_12_growth_loops': D,
    'cdo.funnel_architect': D,
    'cdo.friction': D,
    'cdo.experimentation': D,
    'cao.process_map': D,
    'cao.automation_candidates': D,
    'cao.throughput': D,
    'cso.case_classifier': D,
    'cso.threat_model': D,
    'cso.compliance_map': D,
  },
  authority: {
    ...BASE_DEFERRED_DEPTHS,
    'cmo.agent_1_market': D,
    'cmo.agent_2_awareness_ladder': D,
    'cmo.agent_3_positioning': 'max',
    'cmo.agent_4_voice': D,
    'cmo.agent_5_content_strategy': 'max',
    'cmo.agent_6_viral': D,
    'cmo.agent_7_storytelling': D,
    'cmo.agent_8_ready_posts': D,
    'cmo.agent_9_traffic': 'standard',
    'cmo.agent_10_distribution': D,
    'cmo.agent_11_founder_brand': D,
    'cmo.agent_12_growth_loops': D,
    'cdo.funnel_architect': D,
    'cdo.friction': D,
    'cdo.experimentation': D,
    'cao.process_map': D,
    'cao.automation_candidates': D,
    'cao.throughput': D,
    'cso.case_classifier': D,
    'cso.threat_model': D,
    'cso.compliance_map': D,
  },
  defense: {
    ...BASE_DEFERRED_DEPTHS,
    'cmo.agent_1_market': D,
    'cmo.agent_2_awareness_ladder': D,
    'cmo.agent_3_positioning': 'standard',
    'cmo.agent_4_voice': D,
    'cmo.agent_5_content_strategy': 'min',
    'cmo.agent_6_viral': D,
    'cmo.agent_7_storytelling': D,
    'cmo.agent_8_ready_posts': D,
    'cmo.agent_9_traffic': 'standard',
    'cmo.agent_10_distribution': D,
    'cmo.agent_11_founder_brand': D,
    'cmo.agent_12_growth_loops': D,
    'cdo.funnel_architect': D,
    'cdo.friction': D,
    'cdo.experimentation': D,
    'cao.process_map': D,
    'cao.automation_candidates': D,
    'cao.throughput': D,
    'cso.case_classifier': D,
    'cso.threat_model': D,
    'cso.compliance_map': D,
  },
};
