/**
 * Heuristic flags for HTML that often invalidates a «normal marketing homepage» read (ADR failure-mode matrix).
 * Deterministic string matching only — no bypass of challenges.
 *
 * Optional **taxonomy** slugs are stable for dashboards; booleans stay backward-compatible for clients.
 */

/** WAF / bot-interstitial family (first matching rule wins, most specific to generic). */
export type SnapshotChallengeTaxonomy =
  | 'cloudflare'
  | 'akamai_bot'
  | 'fastly'
  | 'aws_waf'
  | 'imperva_incapsula'
  | 'sucuri'
  | 'stackpath'
  | 'perimeterx'
  | 'datadome'
  | 'generic_bot_interstitial';

/** Parked / placeholder family. */
export type SnapshotParkedTaxonomy =
  | 'for_sale_or_aftermarket'
  | 'registrar_parking_page'
  | 'minimal_placeholder'
  | 'under_construction_hosting';

/** Login / SSO gate family (may overlap challenge in rare pages). */
export type SnapshotLoginWallTaxonomy =
  | 'auth_keyword_copy'
  | 'signin_heading'
  | 'password_field_thin_page'
  | 'oauth_or_sso_form'
  | 'openid_oidc_meta'
  /** Initial HTML is a JS app mount with almost no static copy — real UI likely behind client render or auth. */
  | 'spa_shell_thin_html';

export type PageAnomalyDetection = {
  challengeLikely?: boolean;
  challengeTaxonomy?: SnapshotChallengeTaxonomy;
  parkedLikely?: boolean;
  parkedTaxonomy?: SnapshotParkedTaxonomy;
  loginWallLikely?: boolean;
  loginWallTaxonomy?: SnapshotLoginWallTaxonomy;
};

/** @deprecated Narrow shape; use `PageAnomalyDetection` */
export type PageAnomalyFlags = Pick<
  PageAnomalyDetection,
  'challengeLikely' | 'parkedLikely' | 'loginWallLikely'
>;

/**
 * Generic bot / WAF interstitial copy: language priority ES → EN → DE → CA → RU → IT → (PT, FR, PL, TR, NL, …).
 * Alternation order is for maintainability and slightly better first-hit behaviour on es-heavy pages.
 */
const GENERIC_BOT_INTERSTITIAL_ALT = [
  // es
  'comprobando (su |el )?navegador|verificando (su |el )?navegador|un momento por favor|espere un momento|por favor espere|atenci[oó]n requerida|demuestre que (es |usted es )?humano|verificaci[oó]n de seguridad|verificaci[oó]n del navegador|habilita(r)? javascript|active javascript|protecci[oó]n (anti[- ])?ddos',
  // en
  'checking your browser|attention required|ddos[- ]?protection|just a moment|enable javascript|please wait|ray id|bot check|prove you are human|verify you are human|security check|browser verification|temporarily unavailable.*traffic',
  // de
  'browser wird [üu]berpr[uü]ft|ihr browser wird|einen moment bitte|einen augenblick|sicherheits[üu]berpr[uü]fung|ddos[- ]?schutz|bitte warten',
  // ca
  'comprovant el navegador|esperi un moment|si us plau esperi|verificaci[oó] de seguretat',
  // ru
  'проверка браузера|подождите|докажите что вы человек|проверка безопасности|защита от ddos|включите javascript',
  // it
  'verifica del browser|controllo del browser|attendere prego|un attimo solo|controllo di sicurezza|abilita javascript',
  // pt / fr / pl / tr / nl (after priority six)
  'a verificar o seu navegador|verifica[çc][aã]o de seguran[çc]a|veuillez patienter|une minute|weryfikacja przegl[ąa]darki|chwileczk[eę]|ddos koruma|l[üu]tfen bekleyin|even geduld|browser controleren',
].join('|');

const CHALLENGE_RULES: ReadonlyArray<{ tax: SnapshotChallengeTaxonomy; re: RegExp }> = [
  { tax: 'cloudflare', re: /cf-ray|__cf_bm|cloudflareinsights|cdn-cgi\/challenge|cloudflare bot/i },
  { tax: 'akamai_bot', re: /akamai|akamaighost|ak-bmsc|bot manager akamai/i },
  { tax: 'fastly', re: /\bx-fastly\b|\bx-served-by:\s*fastly|fastly\.com\/iol/i },
  { tax: 'aws_waf', re: /x-amzn-waf|aws.?waf|awswaf|blocked by aws/i },
  { tax: 'imperva_incapsula', re: /incapsula|imperva|visid_incap|incap_ses/i },
  { tax: 'sucuri', re: /sucuri|cloudsproxy\.sucuri/i },
  { tax: 'stackpath', re: /stackpath|spcdn\.com|secureservercdn/i },
  { tax: 'perimeterx', re: /perimeterx|_px[\w-]*|px-captcha|human-verification.*perimeter/i },
  { tax: 'datadome', re: /datadome|dd_(?:cookie|session|verify)|captcha-delivery\.com/i },
  { tax: 'generic_bot_interstitial', re: new RegExp(GENERIC_BOT_INTERSTITIAL_ALT, 'i') },
];

/**
 * Strong parked / placeholder signals (high precision).
 * Language priority: ES → EN → DE → CA → RU → IT → (shared English product strings).
 */
const STRONG_PARKED_ALT = [
  'dominio en venta|comprar (este )?dominio|este dominio (est[áa] )?en venta|dominio aparcado|p[áa]gina de dominio en venta',
  'domain (is )?for sale|buy (this )?domain|purchase (this )?domain|parked (page|domain)|website is coming soon|this page (was )?generated by godaddy|rent this domain|lease this domain|domain.?parking|\\bdomain is available\\b|\\bget this domain\\b',
  'domain zu verkaufen|diese domain kaufen|domain (ist )?zu verkaufen',
  'domini en venda|comprar aquest domini',
  'домен (на )?продаже|купить домен|домен прода[её]тся',
  'dominio in vendita|comprare (questo )?dominio',
  '\\b(sedo|afternic|dan\\.com)\\b',
].join('|');
const STRONG_PARKED_RE = new RegExp(STRONG_PARKED_ALT, 'i');

/** Substrings that indicate aftermarket / for-sale intent (any language), for parked taxonomy. */
const FOR_SALE_DOMAIN_COPY_RE =
  /for sale|buy (this )?domain|purchase|dominio en venta|comprar (este )?dominio|dominio aparcado|domain zu verkaufen|domini en venda|домен (на )?продаже|купить домен|dominio in vendita|este dominio (est[áa] )?en venta/i;

const UNDER_CONSTRUCTION_HOSTING_RE = /under construction\b.*\bhosting|hosting account has been suspended|domain (has )?expired/i;

const REGISTRAR_WEAK_RE = /\b(namecheap|enom|dynadot|porkbun|network solutions|register\.com)\b/i;

const REGISTRAR_PARK_CONTEXT_RE =
  /parked|for sale|is available|buy (this )?domain|domain parking|WHOIS|who.?is|register (this )?domain|web hosting made easy/i;

/**
 * Login-wall body copy: ES → EN → DE → CA → RU → IT → FR, PT, TR, UK, JA, ZH, …
 * (Ukrainian kept after the core six per product preference for Iberia / DACH / RU / IT coverage.)
 */
const LOGIN_KEYWORD_ALT = [
  // es
  'acceso restringido|acceso denegado|debe (?:iniciar sesi[oó]n|identificarse)|inicia(r)? sesi[oó]n(?: para continuar)?|inicie sesi[oó]n|contrase[nñ]a obligatoria|contrase[nñ]a requerida|sesi[oó]n caducada|sesi[oó]n expirada|la sesi[oó]n ha caducado|autenticaci[oó]n requerida|identificaci[oó]n requerida',
  // en
  'sign in (to continue|required)|log in (to continue|to view)|member login|password\\s*required|authentication required|session expired|please login|restricted access|access restricted',
  // de
  'bitte anmelden|anmeldung erforderlich|passwort erforderlich|zugriff verweigert|zugriff beschr[äa]nkt|zugriff eingeschr[äa]nkt|sitzung abgelaufen|ihre sitzung ist abgelaufen|authentifizierung erforderlich',
  // ca
  'acc[ée]s restringit|acc[ée]s denegat|inicia(r)? sessi[oó]|cal iniciar sessi[oó]|contrasenya obligat[òo]ria|contrasenya requerida|sessi[oó] caducada|la sessi[oó] ha caducat',
  // ru
  'доступ ограничен|доступ запрещ[её]н|войдите в систему|вход в систему|войти в систему|требуется (?:авторизация|вход|аутентификация)|пароль обязателен|необходим пароль|сессия истекла|сеанс заверш[её]н|неверный пароль',
  // it
  'accesso riservato|accesso negato|accesso limitato|effettua il login|effettua l[’\u2019]?accesso|password obbligatoria|autenticazione richiesta|sessione scaduta|accesso non autorizzato',
  // fr, pt, tr, uk, ja, zh
  'connexion requise|identification requise|acesso restrito|acesso negado|senha obrigat[óo]ria|zorunlu giri[şs]|giri[şs] yap[ıi]n|доступ обмежено|обмежений доступ|для продовження увійдіть|увійдіть,?\\s*щоб продовжити|щоб продовжити,?\\s*увійдіть|необхідна автентифікація|потрібна автентифікація|необхідний вхід|сеанс закінчився|сеанс завершено|пароль\\s*обов[\'\u2019\u02bc]?язковий|увійти до (?:системи|кабінету|облікового запису)|вхід до (?:системи|кабінету)|доступ (?:лише|тільки) для зареєстрованих|забули пароль\\??|請登入|ログインが必要|需要登录',
].join('|');
const LOGIN_KEYWORD_RE = new RegExp(LOGIN_KEYWORD_ALT, 'i');

/** H1 titles for sign-in gates; same language priority as LOGIN_KEYWORD_ALT (then JA, UK). */
const H1_LOGIN_TITLE_ALT = [
  'iniciar sesi[oó]n|inicia sesi[oó]n|acceder|entrar',
  'sign in|sign-in|log in|log-in|login',
  'anmelden',
  'iniciar sessi[oó]n|inicia sessi[oó]n|accedir',
  'вход|войти|авторизация|аутентификация',
  'accedi|accesso|autenticazione|effettua il login',
  'connexion|se connecter',
  'iniciar sess[aã]o',
  'ログイン',
  'вхід до кабінету|вхід до системи|вхід в особистий кабінет|вхід|увійти|авторизація|автентифікація',
].join('|');
const H1_LOGIN_RE = new RegExp(`<h1[^>]*>\\s*(${H1_LOGIN_TITLE_ALT})\\s*</h1>`, 'i');

const OAUTH_FORM_ACTION_RE =
  /<form[^>]+action=["'][^"']*(?:\/oauth|\/authorize|\/signin|\/sign-in|\/openid|auth0\.com|okta\.com|login\.microsoftonline|accounts\.google)/i;

const OIDC_META_RE =
  /<meta[^>]+(?:property|name)=["'](?:og:url|twitter:url)["'][^>]+content=["'][^"']*(?:\/login|\/signin|openid|oauth)/i;

/** Strip tags to approximate visible text length (first 96KB). */
function approxVisibleTextLen(sample: string): number {
  const noScriptStyle = sample
    .replace(/<script[\s\S]*?<\/script>/gi, ' ')
    .replace(/<style[\s\S]*?<\/style>/gi, ' ')
    .replace(/<noscript[\s\S]*?<\/noscript>/gi, ' ');
  const text = noScriptStyle.replace(/<[^>]+>/g, ' ').replace(/\s+/g, ' ').trim();
  return text.length;
}

function countOpenScriptTags(sample: string): number {
  return (sample.match(/<script\b/gi) ?? []).length;
}

/** Same-origin path links only (leading slash, not protocol-relative). */
function countPathInternalAnchors(sample: string): number {
  return (sample.match(/<a[^>]+href=["']\/[^"'#/]/gi) ?? []).length;
}

function hasSpaShellMountMarkers(sample: string): boolean {
  return (
    /<(div|section)[^>]+id=["'](root|__next|app|vue-app|ng-app|react-root|__nuxt)["']/i.test(sample) ||
    /id=["']__nuxt["']/i.test(sample) ||
    /__NEXT_DATA__|window\.__(?:NUXT|STATIC_CONTENT__)|data-reactroot|"reactroot"/i.test(sample)
  );
}

/**
 * Live site signals to avoid flagging registrar/parking **weak** hints on real SMB pages
 * (footer “Hosted by X”, long copy + schema, contact paths).
 */
function shouldSuppressWeakParkedHint(sample: string, visibleApprox: number): boolean {
  const ld = sample;
  const hasLocalBizSignal =
    /["']?@type["']?\s*:\s*["']LocalBusiness["']/i.test(ld) &&
    (/telephone|streetAddress|PostalAddress|openingHours/i.test(ld) ||
      /"address"\s*:\s*\{/.test(ld));

  const hasOrgContactSignal =
    /["']?@type["']?\s*:\s*["'](?:Organization|ProfessionalService|Corporation)["']/i.test(ld) &&
    /contactPoint|telephone|"address"|streetAddress/i.test(ld);

  const hasContactScheme = /mailto:|tel:\+?[\d\s\-()]+/i.test(sample);
  const pathLinks = countPathInternalAnchors(sample);

  if (hasLocalBizSignal) return true;
  if (hasOrgContactSignal && visibleApprox >= 350) return true;
  if (hasContactScheme && visibleApprox >= 650) return true;
  if (pathLinks >= 12 && visibleApprox >= 550) return true;
  if (pathLinks >= 8 && visibleApprox >= 1_800) return true;
  if (visibleApprox >= 3_200) return true;

  return false;
}

/** Inspect first ~96KB — enough for typical interstitial + head. */
export function detectPageAnomalies(html: string, finalUrl: string): PageAnomalyDetection {
  const sample = html.slice(0, 96_000);
  const lower = sample.toLowerCase();
  const visibleApprox = approxVisibleTextLen(sample);
  const rawMarkupLen = lower
    .replace(/<script[\s\S]*?<\/script>/gi, ' ')
    .replace(/<style[\s\S]*?<\/style>/gi, ' ')
    .length;

  let challengeTaxonomy: SnapshotChallengeTaxonomy | undefined;
  for (const { tax, re } of CHALLENGE_RULES) {
    if (re.test(sample)) {
      challengeTaxonomy = tax;
      break;
    }
  }
  const challengeLikely = challengeTaxonomy !== undefined;

  let parkedTaxonomy: SnapshotParkedTaxonomy | undefined;
  let parkedLikely = false;
  /** True only for registrar-weak or thin-context branch (can be suppressed for live SMB). */
  let parkedFromWeakRegistrar = false;

  if (STRONG_PARKED_RE.test(lower)) {
    parkedLikely = true;
    parkedTaxonomy = /sedo|afternic|dan\.com/i.test(sample)
      ? 'for_sale_or_aftermarket'
      : FOR_SALE_DOMAIN_COPY_RE.test(lower)
        ? 'for_sale_or_aftermarket'
        : 'minimal_placeholder';
  } else if (UNDER_CONSTRUCTION_HOSTING_RE.test(lower)) {
    parkedLikely = true;
    parkedTaxonomy = 'under_construction_hosting';
  } else if (REGISTRAR_WEAK_RE.test(lower)) {
    const thin = visibleApprox < 3_800;
    const ctx = REGISTRAR_PARK_CONTEXT_RE.test(lower);
    if (thin || ctx) {
      parkedFromWeakRegistrar = true;
      parkedLikely = true;
      parkedTaxonomy = 'registrar_parking_page';
    }
  }

  if (parkedLikely && (parkedFromWeakRegistrar || parkedTaxonomy === 'registrar_parking_page')) {
    if (shouldSuppressWeakParkedHint(sample, visibleApprox)) {
      parkedLikely = false;
      parkedTaxonomy = undefined;
      parkedFromWeakRegistrar = false;
    }
  }

  let loginWallTaxonomy: SnapshotLoginWallTaxonomy | undefined;
  let loginWallLikely = false;

  if (LOGIN_KEYWORD_RE.test(lower)) {
    loginWallLikely = true;
    loginWallTaxonomy = 'auth_keyword_copy';
  } else if (H1_LOGIN_RE.test(sample)) {
    loginWallLikely = true;
    loginWallTaxonomy = 'signin_heading';
  } else if (OIDC_META_RE.test(sample)) {
    loginWallLikely = true;
    loginWallTaxonomy = 'openid_oidc_meta';
  } else if (
    OAUTH_FORM_ACTION_RE.test(sample) &&
    /<input[^>]+type=["']email["']/i.test(sample) &&
    rawMarkupLen < 16_000 &&
    !/newsletter|subscribe to our/i.test(lower)
  ) {
    loginWallLikely = true;
    loginWallTaxonomy = 'oauth_or_sso_form';
  } else if (
    /<input[^>]+type=["']password["']/i.test(sample) &&
    rawMarkupLen < 12_000 &&
    !/newsletter|subscribe/i.test(lower)
  ) {
    loginWallLikely = true;
    loginWallTaxonomy = 'password_field_thin_page';
  }

  const scripts = countOpenScriptTags(sample);
  const path = (() => {
    try {
      return new URL(finalUrl).pathname;
    } catch {
      return '/';
    }
  })();
  const pathSuggestsAppShell = path === '/' || /\/(?:app|dashboard|portal|account)\/?$/i.test(path);

  if (
    !loginWallLikely &&
    !challengeLikely &&
    !parkedLikely &&
    pathSuggestsAppShell &&
    visibleApprox < 520 &&
    scripts >= 10 &&
    hasSpaShellMountMarkers(sample)
  ) {
    loginWallLikely = true;
    loginWallTaxonomy = 'spa_shell_thin_html';
  }

  const out: PageAnomalyDetection = {};
  if (challengeLikely) {
    out.challengeLikely = true;
    if (challengeTaxonomy) out.challengeTaxonomy = challengeTaxonomy;
  }
  if (parkedLikely) {
    out.parkedLikely = true;
    if (parkedTaxonomy) out.parkedTaxonomy = parkedTaxonomy;
  }
  if (loginWallLikely) {
    out.loginWallLikely = true;
    if (loginWallTaxonomy) out.loginWallTaxonomy = loginWallTaxonomy;
  }
  return out;
}

export function anomalyLimitationMessages(flags: PageAnomalyFlags): string[] {
  const lim: string[] = [];
  if (flags.challengeLikely) {
    lim.push(
      'Sampled HTML resembles a bot challenge, WAF interstitial, or anti-automation page — automated scoring may not reflect what human visitors see.',
    );
  }
  if (flags.parkedLikely) {
    lim.push(
      'The page resembles a parked, for-sale, or placeholder domain — treat any business profile as low confidence.',
    );
  }
  if (flags.loginWallLikely) {
    lim.push(
      'The public HTML looks like a sign-in gate or a thin SPA shell — most real content may load only in the browser or behind login.',
    );
  }
  return lim;
}
