/**
 * Canonical defaults for server behaviour (static CONFIG layer).
 * Prefer adding tunables in this folder; use `process.env` only for secrets, deploy wiring, or
 * documented infra needs (see `server/.env.example`).
 */

import { SYSTEM_DEFAULTS_ALERTS, SYSTEM_DEFAULTS_CONTEXT_BUILDER, SYSTEM_DEFAULTS_OBSERVABILITY } from './alerts-observability-context.js';
import { SYSTEM_DEFAULTS_ANTHROPIC_ALTERNATE_MODEL_PRICING_USD_PER_MTOK, SYSTEM_DEFAULTS_AGENT_PERSISTENCE, SYSTEM_DEFAULTS_CLAUDE_HTTP, SYSTEM_DEFAULTS_PIPELINE_MODEL, SYSTEM_DEFAULTS_TOKEN_TRACKER } from './pipeline-model-and-claude.js';
import { SYSTEM_DEFAULTS_AUDIT_DEEP_SCAN, SYSTEM_DEFAULTS_LIGHTHOUSE_RUN } from './audit-deep-scan-lighthouse.js';
import { SYSTEM_DEFAULTS_OUTBOUND_BOT, SYSTEM_DEFAULTS_PLAYWRIGHT_SNAPSHOT_USER_AGENT } from './bots-and-ua.js';
import {
  SYSTEM_DEFAULTS_COLLECTOR_CACHE_TTL_MS,
  SYSTEM_DEFAULTS_COLLECTORS_HTTP,
  SYSTEM_DEFAULTS_COLLECTORS_SAMPLING,
  SYSTEM_DEFAULTS_CRAWLER,
  SYSTEM_DEFAULTS_TECH_TENTATIVE,
  SYSTEM_DEFAULTS_TECH_WAPPALYZER,
} from './collectors-and-crawler.js';
import { SYSTEM_DEFAULTS_CONNECTORS } from './connectors.js';
import { SYSTEM_DEFAULTS_EXECUTION_PLAN } from './execution-plan.js';
import { SYSTEM_DEFAULTS_EXPRESS } from './express.js';
import { SYSTEM_DEFAULTS_FEATURE_FLAGS } from './feature-flags-defaults.js';
import { SYSTEM_DEFAULTS_INTAKE } from './intake.js';
import { SYSTEM_DEFAULTS_IDEMPOTENCY, SYSTEM_DEFAULTS_UPGRADE_FREE_SNAPSHOT_PREFILL } from './misc.js';
import {
  SYSTEM_DEFAULTS_AGENT_PERFORMANCE,
  SYSTEM_DEFAULTS_BANDITS,
  SYSTEM_DEFAULTS_BENCHMARKS,
  SYSTEM_DEFAULTS_EVALUATION_DATASETS,
} from './ml-and-eval.js';
import { SYSTEM_DEFAULTS_PIPELINE_ORCHESTRATOR, SYSTEM_DEFAULTS_PIPELINE_QUEUE, SYSTEM_DEFAULTS_PIPELINE_WORKER } from './pipeline-infra.js';
import { SYSTEM_DEFAULTS_PUBLIC_ROUTE_RATE_LIMITS, SYSTEM_DEFAULTS_RATE_LIMITS } from './rate-limits.js';
import { SYSTEM_DEFAULTS_AUTO_REMEDIATION } from './remediation.js';
import { SYSTEM_DEFAULTS_REPORT_PDF, SYSTEM_DEFAULTS_REPORT_PROFILER } from './reports.js';
import { SYSTEM_DEFAULTS_AUDITS_LIST, SYSTEM_DEFAULTS_ROUTE_QUERIES } from './route-queries.js';
import { SYSTEM_DEFAULTS_SNAPSHOT_AUDIT } from './snapshot/audit-evaluator.js';
import {
  SYSTEM_DEFAULTS_PAGE_ANOMALY,
  SYSTEM_DEFAULTS_SNAPSHOT_ABUSE,
  SYSTEM_DEFAULTS_SNAPSHOT_CLASSIFICATION,
  SYSTEM_DEFAULTS_SNAPSHOT_DOMAIN_CACHE,
  SYSTEM_DEFAULTS_SNAPSHOT_LINK_SLUG,
  SYSTEM_DEFAULTS_SNAPSHOT_ROBOTS,
} from './snapshot/guards-cache-slug.js';
import { SYSTEM_DEFAULTS_SNAPSHOT_GUEST_SESSION, SYSTEM_DEFAULTS_SNAPSHOT_PUBLIC } from './snapshot/public-and-session.js';
import {
  SYSTEM_DEFAULTS_SNAPSHOT_FETCH_BUDGET_MS,
  SYSTEM_DEFAULTS_SNAPSHOT_TIMING,
  SYSTEM_DEFAULTS_SNAPSHOT_TIERED_FETCH,
} from './snapshot/timing-and-fetch.js';
import {
  SYSTEM_DEFAULTS_AUTO_LOOP,
  SYSTEM_DEFAULTS_DECISION_LAYER,
  SYSTEM_DEFAULTS_QUALITY_GATE,
  SYSTEM_DEFAULTS_STRATEGY_NARROW_GOVERNANCE,
} from './quality-decision-loop.js';

export const SYSTEM_DEFAULTS = {
  express: SYSTEM_DEFAULTS_EXPRESS,
  rateLimits: SYSTEM_DEFAULTS_RATE_LIMITS,
  auditsList: SYSTEM_DEFAULTS_AUDITS_LIST,
  routeQueries: SYSTEM_DEFAULTS_ROUTE_QUERIES,
  intake: SYSTEM_DEFAULTS_INTAKE,
  reportProfiler: SYSTEM_DEFAULTS_REPORT_PROFILER,
  collectorsSampling: SYSTEM_DEFAULTS_COLLECTORS_SAMPLING,
  techTentative: SYSTEM_DEFAULTS_TECH_TENTATIVE,
  crawler: SYSTEM_DEFAULTS_CRAWLER,
  collectorsHttp: SYSTEM_DEFAULTS_COLLECTORS_HTTP,
  techWappalyzer: SYSTEM_DEFAULTS_TECH_WAPPALYZER,
  snapshotPublic: SYSTEM_DEFAULTS_SNAPSHOT_PUBLIC,
  snapshotGuestSession: SYSTEM_DEFAULTS_SNAPSHOT_GUEST_SESSION,
  idempotency: SYSTEM_DEFAULTS_IDEMPOTENCY,
  snapshotAudit: SYSTEM_DEFAULTS_SNAPSHOT_AUDIT,
  snapshotFetchBudgetMs: SYSTEM_DEFAULTS_SNAPSHOT_FETCH_BUDGET_MS,
  collectorCacheTtlMs: SYSTEM_DEFAULTS_COLLECTOR_CACHE_TTL_MS,
  alerts: SYSTEM_DEFAULTS_ALERTS,
  observability: SYSTEM_DEFAULTS_OBSERVABILITY,
  contextBuilder: SYSTEM_DEFAULTS_CONTEXT_BUILDER,
  publicRouteRateLimits: SYSTEM_DEFAULTS_PUBLIC_ROUTE_RATE_LIMITS,
  pipelineModel: SYSTEM_DEFAULTS_PIPELINE_MODEL,
  anthropicAlternateModelPricingUsdPerMtok: SYSTEM_DEFAULTS_ANTHROPIC_ALTERNATE_MODEL_PRICING_USD_PER_MTOK,
  tokenTracker: SYSTEM_DEFAULTS_TOKEN_TRACKER,
  claudeHttp: SYSTEM_DEFAULTS_CLAUDE_HTTP,
  agentPersistence: SYSTEM_DEFAULTS_AGENT_PERSISTENCE,
  connectors: SYSTEM_DEFAULTS_CONNECTORS,
  qualityGate: SYSTEM_DEFAULTS_QUALITY_GATE,
  bandits: SYSTEM_DEFAULTS_BANDITS,
  evaluationDatasets: SYSTEM_DEFAULTS_EVALUATION_DATASETS,
  featureFlags: SYSTEM_DEFAULTS_FEATURE_FLAGS,
  autoLoop: SYSTEM_DEFAULTS_AUTO_LOOP,
  decisionLayer: SYSTEM_DEFAULTS_DECISION_LAYER,
  strategyNarrowGovernance: SYSTEM_DEFAULTS_STRATEGY_NARROW_GOVERNANCE,
  executionPlan: SYSTEM_DEFAULTS_EXECUTION_PLAN,
  agentPerformance: SYSTEM_DEFAULTS_AGENT_PERFORMANCE,
  autoRemediation: SYSTEM_DEFAULTS_AUTO_REMEDIATION,
  benchmarks: SYSTEM_DEFAULTS_BENCHMARKS,
  pipelineOrchestrator: SYSTEM_DEFAULTS_PIPELINE_ORCHESTRATOR,
  pipelineWorker: SYSTEM_DEFAULTS_PIPELINE_WORKER,
  pipelineQueue: SYSTEM_DEFAULTS_PIPELINE_QUEUE,
  snapshotTiming: SYSTEM_DEFAULTS_SNAPSHOT_TIMING,
  snapshotAbuse: SYSTEM_DEFAULTS_SNAPSHOT_ABUSE,
  snapshotRobots: SYSTEM_DEFAULTS_SNAPSHOT_ROBOTS,
  snapshotDomainCache: SYSTEM_DEFAULTS_SNAPSHOT_DOMAIN_CACHE,
  snapshotLinkSlug: SYSTEM_DEFAULTS_SNAPSHOT_LINK_SLUG,
  snapshotTieredFetch: SYSTEM_DEFAULTS_SNAPSHOT_TIERED_FETCH,
  snapshotClassification: SYSTEM_DEFAULTS_SNAPSHOT_CLASSIFICATION,
  pageAnomaly: SYSTEM_DEFAULTS_PAGE_ANOMALY,
  auditDeepScan: SYSTEM_DEFAULTS_AUDIT_DEEP_SCAN,
  lighthouseRun: SYSTEM_DEFAULTS_LIGHTHOUSE_RUN,
  playwrightSnapshotUserAgent: SYSTEM_DEFAULTS_PLAYWRIGHT_SNAPSHOT_USER_AGENT,
  outboundBot: SYSTEM_DEFAULTS_OUTBOUND_BOT,
  upgradeFreeSnapshotPrefill: SYSTEM_DEFAULTS_UPGRADE_FREE_SNAPSHOT_PREFILL,
  reportPdf: SYSTEM_DEFAULTS_REPORT_PDF,
} as const;
