export const FACT_EXTRACTION_REGEX = {
  ctaVerb:
    /(book|start|get|request|contact|schedule|demo|try|call|quote|buy|add to cart|checkout|subscribe|sign up|free trial)/i,
  genericMarketing:
    /\b(growth|excellence|trusted partner|innovation|empower|transform|solutions?\s+for\s+everyone)\b/i,
  aiTxtLink: /\b\/ai\.txt\b|\bai\.txt\b/i,
  sitemapFile: /sitemap[^"'?\s]*\.(xml|txt)(\?|$)/i,
  sitemapIndex: /sitemap[_-]?(index|_index)?\.xml/i,
  openingHours: /opening hours|open\s+now|monday|tuesday|wednesday|hours:/i,
  addressish: /street|avenue|boulevard|postal code|zip code|\b\d{5}\b/,
  pricing: /\$|€|£|pricing|plans?|per month|\/mo\b/,
  process: /how it works|our process|step\s*1/i,
  noindex: /noindex/i,
  viewportWidth: /width/i,
  phoneInHtml: /\+\d[\d\s().-]{8,}/,
  homepageShellMount: /id=["']root["']|id=["']__next["']|data-reactroot/i,
  sitemapRelInRawHtml: /rel=["']sitemap["']/i,
  llmsHrefInRawHtml: /href=["'][^"']*llms\.txt/i,
  aiTxtHrefInRawHtml: /href=["'][^"']*\/ai\.txt/i,
} as const;

export const TITLE_TOKEN_STOP_WORDS = new Set([
  'the',
  'and',
  'for',
  'your',
  'our',
  'with',
  'from',
  'that',
  'this',
  'are',
  'was',
  'but',
  'not',
  'you',
  'all',
  'can',
  'has',
  'how',
  'its',
  'may',
  'new',
  'now',
  'see',
  'way',
  'who',
  'get',
  'use',
  'year',
  'day',
  'com',
  'www',
  'home',
  'page',
  'site',
  'web',
  'best',
  'free',
  'more',
  'inc',
  'llc',
  'ltd',
  'corp',
]);
