/**
 * Re-export shared API paths (canonical definitions live in `@glc/api-paths`).
 */

export {
  API_PATHS,
  type ApiLogPath,
  apiBenchmarksQuery,
  apiAuditsBriefHelpRequest,
  apiAuditsPath,
  apiAuditsPipelineNext,
  apiAuditsPipelineRetry,
  apiAuditsPipelineStart,
  apiAuditsPipelineStop,
  apiAuditsPipelineStatus,
  apiAuditsStrategyExecutionPack,
  apiAuditsStrategyExecutionPacks,
  apiAuditsStrategyLabContext,
  apiAuditsRoadmapManifestPreview,
  apiAuditsRoadmapManifestSnapshots,
  apiAuditsRoadmapManifestSnapshotsLatest,
  apiAuditsOrchestrationPack,
  apiAuditsOrchestrationSelectedInitiative,
  apiAuditsOrchestrationPackRegenerate,
  apiAuditsOrchestrationPackDiff,
  apiAuditsOrchestrationPackDiffHistory,
  apiAuditsOrchestrationCommercialOffer,
  apiAuditsOrchestratorPreview,
  apiAuditsOrchestratorRun,
  apiAuditsOrchestratorLatest,
  apiAuditsTimeline,
  apiAuditsDirectorDeepDive,
  apiAuditsDirectorDeepDiveStatus,
  apiAuditsDirectorDeepDiveQuota,
  apiPlatformAuditPipelineResumeCancelled,
  apiAuditsQualityGate,
  apiAuditsReportQuery,
  apiAuditsReview,
  apiIntakePrefill,
  apiIntakeIntelligenceKpi,
  apiIntakeNlDescribe,
  apiIntakeRespond,
  apiIntakeToken,
  apiBriefPublicSession,
  apiBriefPublicSubmit,
  apiBriefPublicConvert,
  apiIntakeTracePublicationLog,
} from '@glc/api-paths';
