export const COALITION_PROTOCOL_COPY = {
  monitor: {
    sectionTitle: 'Coalition director rounds',
    contextDirector: 'Client situation snapshot',
    hypothesis: 'Hypothesis round',
    alignment: 'Alignment round',
    resolver: 'Conflict resolver',
    finalized: 'Finalize prompts use coalition context',
    pending: 'Waiting for coalition events',
    active: 'Active',
    complete: 'Complete',
    conflictEscalation: 'Conflict escalation required',
  },
  gate: {
    approveCoalitionTitle: 'Approve client situation',
    approveCoalitionBody:
      'Review the shared situation snapshot before final domain recommendations use coalition context.',
    snapshotHeading: 'Client situation snapshot',
    noSnapshot: 'No coalition snapshot has been saved for this audit yet.',
    editHeading: 'Verified situation override',
    editIntro: 'Optional: correct the essential fields before approving. These values are appended to consultant notes as a server-verified override.',
    entityType: 'Entity type',
    dominantConstraint: 'Dominant constraint',
    strategicMode: 'Strategic mode',
    maturity: 'Maturity',
    productClarity: 'Product clarity',
    audienceClarity: 'Audience clarity',
    positioningStrength: 'Positioning strength',
    channelReadiness: 'Channel readiness',
    resourceConstraints: 'Resource constraints',
  },
  clientSituationCard: {
    title: 'Client situation',
    empty: 'No client situation snapshot is available yet.',
    entityType: 'Entity type',
    dominantConstraint: 'Dominant constraint',
    strategicMode: 'Strategic mode',
    dataQuality: 'Data quality',
    maturity: 'Maturity',
    assumptions: 'Assumptions',
    questions: 'Clarifying questions',
  },
  conflictMatrix: {
    title: 'Conflict matrix',
    empty: 'No cross-domain conflicts have been recorded.',
    resolved: 'Resolved conflicts',
    unresolved: 'Unresolved conflicts',
    parties: 'Parties',
    decision: 'Decision',
    recommendedAction: 'Recommended action',
  },
  chain: {
    title: 'Coalition chain',
    empty: 'No coalition hypothesis chain is available yet.',
    hypotheses: 'Hypotheses',
    corrections: 'Self-corrections',
    dependencies: 'Cross-domain dependencies',
  },
} as const;
