/**
 * Client-side subset of server deep-dive error codes.
 * Keep in sync with `server/src/config/api-error-codes.ts`.
 */
export const DIRECTOR_DEEP_DIVE_API_ERROR_CODES = {
  DIRECTOR_DEEP_DIVE_DISABLED: 'DIRECTOR_DEEP_DIVE_DISABLED',
  DIRECTOR_DEEP_DIVE_PAYLOAD_INVALID: 'DIRECTOR_DEEP_DIVE_PAYLOAD_INVALID',
  DIRECTOR_DEEP_DIVE_QUOTA_EXCEEDED: 'DIRECTOR_DEEP_DIVE_QUOTA_EXCEEDED',
  DIRECTOR_DEEP_DIVE_JOB_NOT_FOUND: 'DIRECTOR_DEEP_DIVE_JOB_NOT_FOUND',
  DIRECTOR_DEEP_DIVE_FAILED: 'DIRECTOR_DEEP_DIVE_FAILED',
  DIRECTOR_DEEP_DIVE_DEAD_LETTER: 'DIRECTOR_DEEP_DIVE_DEAD_LETTER',
} as const;

export type DirectorDeepDiveApiErrorCode =
  (typeof DIRECTOR_DEEP_DIVE_API_ERROR_CODES)[keyof typeof DIRECTOR_DEEP_DIVE_API_ERROR_CODES];
