/**
 * Intake trace tool — internal consultant debugger (`/admin/intake-trace`).
 */

export const INTAKE_TRACE_TOOL_COPY = {
  title: 'Intake plan trace',
  subtitle: 'Runs buildIntakePlan locally — same resolver as the server CLI (debug only)',
  responsesNotObject: 'Responses must be a JSON object.',
  invalidJson: 'Invalid JSON in responses.',
  legacyBannerPrefix: 'Legacy Intake trace layout: enable the workspace UI via',
  legacyBannerMonoFlag: 'APP_FEATURE_FLAGS.intakeTraceIaV2Enabled',
  legacyBannerMonoPath: 'src/app/config/app-feature-flags.ts',
  introConsultantOnly: 'Consultant-only tool.',
  introIaV2Part1: 'Start in ',
  introIaV2Diagnose: 'Diagnose',
  introIaV2Part2: ' for question-level reasoning, open ',
  introIaV2Advanced: 'Advanced',
  introIaV2Part3: ' for raw resolver outputs. Draft copy lives in ',
  introIaV2WordingLink: 'Intake wording',
  introIaV2Part4: '.',
  introLegacyUse: 'Use ',
  introLegacyQuestionTrace: 'Question trace',
  introLegacyForReasons: ' for ',
  introLegacySemicolon: '; ',
  introLegacyPlanJson: 'Plan JSON',
  introLegacyForMissing: ' for ',
  introLegacySlash: ' / ',
  introLegacyEnd: '.',
  startHereSummary: 'Start here',
  startHereSteps:
    '1) Pick a preset. 2) Open "Why this question appears". 3) Use Dependencies graph only if the cause is still unclear.',
  workspaceLabel: 'Workspace',
  diagnose: 'Diagnose',
  advanced: 'Advanced',
  viewModeLabel: 'View mode',
  simple: 'Simple',
  expert: 'Expert',
  productMode: 'Product mode',
  collectionMode: 'Collection mode',
  surface: 'Surface',
  responsesJsonLabel: 'Responses (JSON object)',
  eligibleVisible: 'Eligible / visible',
  requiredCount: 'Required (count)',
  missingForReport: 'missingForReport',
  nextRecommended: 'nextRecommended',
  emDash: '—',
  wordingMovedIaV2:
    'Draft editing moved to',
  wordingWorkspaceLink: 'Intake wording workspace',
  wordingMovedIaV2Suffix: '. Labels below still reflect your saved drafts for trace views.',
  wordingLegacyIntro:
    'Draft wording: local + server sync. Open',
  wordingLegacyLink: 'Intake wording',
  wordingLegacyIntroSuffix: ' for a focused editor.',
  questionId: 'Question id',
  currentCanonLabel: 'Current canon label:',
  draftWording: 'Draft wording',
  draftPlaceholder: 'Write a clearer wording for this question...',
  saveDraftLocal: 'Save draft (local)',
  revertEditor: 'Revert editor',
  syncToServer: 'Sync to server',
  copyJson: 'Copy JSON',
  serverSyncOk: 'Server sync OK',
  serverSyncFailed: 'Server sync failed',
  emptyTraceHint: 'Adjust inputs to refresh trace.',
  panelLabel: {
    treeLegacy: 'Question trace',
    treeIaV2: 'Why this question appears',
    journey: 'User journey',
    branchLegacy: 'Branch map',
    branchIaV2: 'Dependencies graph',
    traceLegacy: 'Trace text',
    traceIaV2: 'Resolver log',
    json: 'Plan JSON',
    wording: 'Wording drafts',
  } as const,
  panelHint: {
    tree: 'Inspect reasons and states per question id.',
    journey: 'Review what users see step by step.',
    branch: 'Inspect upstream/downstream branch dependencies.',
    trace: 'Read the raw resolver trace text output.',
    json: 'Inspect the full resolver tuple and plan internals.',
    wording: 'Edit local wording drafts (open Wording workspace for focused editing).',
  } as const,
} as const;
