/**
 * Subset of server `API_ERROR_CODES` for `POST /api/audits/:id/strategy/execution-pack`.
 * Keep aligned with `server/src/config/api-error-codes.ts`.
 */
export const STRATEGY_EXECUTION_PACK_API_ERROR_CODES = {
  STRATEGY_EXECUTION_PACK_DISABLED: 'STRATEGY_EXECUTION_PACK_DISABLED',
  AUDITS_STRATEGY_EXECUTION_PACK_NOT_READY: 'AUDITS_STRATEGY_EXECUTION_PACK_NOT_READY',
  AUDITS_STRATEGY_EXECUTION_PACK_PAYLOAD_INVALID: 'AUDITS_STRATEGY_EXECUTION_PACK_PAYLOAD_INVALID',
  AUDITS_STRATEGY_EXECUTION_PACK_FAILED: 'AUDITS_STRATEGY_EXECUTION_PACK_FAILED',
  AUDITS_NOT_FOUND: 'AUDITS_NOT_FOUND',
} as const;
