/** Shared typographic placeholder for empty table/export fields (copy layer). */
const STRATEGY_LAB_EMPTY_FIELD = '—' as const;

export const STRATEGY_LAB_COPY = {
  tabLabels: {
    quick: 'Quick Wins',
    medium: 'Core Growth',
    strategic: 'Strategic',
  },
  appShell: {
    title: 'Strategy Lab',
    subtitle: 'Build a prioritised transformation roadmap',
    loadingSubtitle: 'Loading...',
    errorSubtitle: 'Error',
    unavailableSubtitle: 'Not available yet',
  },
  export: {
    documentTitle: 'Prioritised transformation roadmap',
    companyLabel: 'Company',
    urlLabel: 'URL',
    auditIdLabel: 'Audit ID',
    generatedOnLabel: 'Generated (UTC)',
    executiveSummaryHeading: 'Executive summary',
    selectedInitiativesHeading: 'Selected initiatives',
    impactLabel: 'Impact',
    effortLabel: 'Effort',
    dependenciesLabel: 'Dependencies',
    missingFieldValue: STRATEGY_LAB_EMPTY_FIELD,
  },
  toasts: {
    roadmapDownloaded: 'Roadmap downloaded as a Markdown file.',
  },
  panel: {
    filterDomainLabel: 'Filter by domain',
    sortModeLabel: 'Sort',
    sortModes: {
      impact: 'By impact',
      effort: 'By effort',
      roi: 'By ROI score',
      domain: 'By domain',
    },
    domainFilterAll: 'All domains',
    generateExecutionPlan: 'Generate execution plan',
    executionPlanRunning: 'Generating execution plan…',
    executionPlanDone: 'Execution plan saved',
    executionPlanFailed: 'Could not generate execution plan',
    executionPlanTooMany: 'Select at most {max} initiatives for an execution plan.',
    initiativeDetails: 'Details',
    labels: {
      why: 'Why this',
      outcome: 'Outcome',
      scopeIn: 'In scope',
      scopeOut: 'Out of scope',
      paths: 'Execution paths',
      evidence: 'Evidence',
      verified: 'Evidence links verified',
      unverified: 'Evidence links not fully verified',
      incompatible: 'Incompatible with brief constraints',
    },
    lastExecutionPlan: 'Latest execution plan',
    noExecutionPlans: 'No execution plans yet',
    selectedSuffix: 'selected',
    generateRoadmap: 'Generate Roadmap',
    domainBenchmarksTitle: 'Domain benchmarks',
    domainBenchmarksHint:
      'Median confidence (p50) vs peer runs in the last 90 days. Uses your audit industry when set, otherwise the cross-industry pool.',
    emptyBenchmarksValue: STRATEGY_LAB_EMPTY_FIELD,
    noInitiativesInCategory: 'No initiatives in this category',
    yourRoadmap: 'Your Roadmap',
    initiativesSelectedSuffix: 'initiatives selected',
    totalInitiatives: 'Total Initiatives',
    quickWins: 'Quick Wins',
    strategicItems: 'Strategic Items',
    effortMix: 'Effort Mix',
    selectedTitle: 'Selected',
    moreItemsSuffix: 'more items',
    viewReport: 'View Report',
    roadmapPreviewTitle: 'Roadmap document',
    roadmapPreviewHint: 'Same text as the Markdown download. Scroll to read.',
    roadmapPreviewEmpty: 'Select one or more initiatives on the left to preview the roadmap here.',
  },
  messages: {
    auditNotFound: 'Audit not found',
    notGenerated: 'Strategy data not yet generated',
    completePipeline: 'Complete the pipeline to generate strategy',
  },
  constraints: {
    sectionTitle: 'Constraint assumptions',
    sectionHint:
      'These values drive initiative constraint rules (for example scalable paths vs budget). Saved values override the intake brief until you clear them.',
    companyStage: 'Company stage',
    budgetBand: 'Budget band',
    teamScale: 'Team size',
    save: 'Save overrides',
    useBrief: 'Clear overrides (use intake brief)',
    saveOk: 'Constraint overrides saved.',
    clearOk: 'Overrides cleared. Intake brief values apply again.',
    saveFailed: 'Could not save constraint overrides.',
    optionLabels: {
      stage: {
        idea: 'Idea',
        mvp: 'MVP',
        growth: 'Growth',
        scale: 'Scale',
        stabilization: 'Stabilisation',
      },
      budget: {
        unknown: 'Unknown / not shared',
        low: 'Low',
        medium: 'Medium',
        high: 'High',
      },
      team: {
        solo: 'Solo',
        small: '2–10 people',
        medium: '11–50',
        large: '51–200',
        enterprise: '200+',
        unknown: 'Unknown / not shared',
      },
    },
  },
} as const;
