import { LEGAL_CONTRACT_DEFAULTS, TERMS_DOCUMENT_LAST_UPDATED_EN } from './legal-contract-defaults';
import { LEGAL_DOC_PAGES_EN } from './legal-doc-pages-copy.en';

export type TermsBlock =
  | { readonly type: 'paragraph'; readonly text: string }
  | { readonly type: 'list'; readonly items: readonly string[] };

export type TermsSubsection = {
  readonly id: string;
  readonly title: string;
  readonly blocks: readonly TermsBlock[];
};

export type TermsSection = {
  readonly id: string;
  readonly title: string;
  readonly blocks?: readonly TermsBlock[];
  readonly subsections?: readonly TermsSubsection[];
};

const INVOICE_PAYMENT_SENTENCE = `Unless otherwise agreed, invoices are payable within ${String(LEGAL_CONTRACT_DEFAULTS.invoicePaymentDaysFromIssue)} days from their date of issuance.`;

export const TERMS_OF_SERVICE_PAGE_EN = {
  documentTitle: 'Terms of Service | GLC',
  htmlLang: 'en' as const,
  titlePrimary: 'Terms of Service',
  titleSecondary: 'Condiciones de Contratación',
  lastUpdatedLabel: 'Last updated',
  lastUpdatedValue: TERMS_DOCUMENT_LAST_UPDATED_EN,
  backToLogin: LEGAL_DOC_PAGES_EN.backToLogin,
  sections: [
    {
      id: 'definitions',
      title: '1. Definitions',
      blocks: [
        {
          type: 'list',
          items: [
            '"Company", "GLC", "we", "us" — Alena Dziadkova (NIF Z3331966F), acting under the trade name "GLC", established in Spain.',
            '"Client" — any individual or legal entity contracting or using the Service.',
            '"Service" — audit, analysis, reporting, strategy development, and optional implementation services provided by GLC.',
            '"Deliverables" — reports, roadmaps, recommendations, analyses and other outputs generated by GLC in the context of the Service.',
            '"Data" — any information, including personal data, provided by the Client or collected on the Client\'s behalf for the provision of the Service.',
          ],
        },
        {
          type: 'paragraph',
          text: 'When GLC processes personal data on behalf of the Client, the Client will generally act as "data controller" and GLC as "data processor", as further detailed in the Data Processing Agreement (DPA), where applicable.',
        },
      ],
    },
    {
      id: 'scope',
      title: '2. Scope of Services',
      blocks: [
        {
          type: 'paragraph',
          text: 'GLC provides analytical and advisory services, including but not limited to:',
        },
        {
          type: 'list',
          items: [
            'business and technical audits',
            'process and infrastructure analysis',
            'strategic recommendations and roadmaps',
            'optional implementation support and follow-up sessions',
          ],
        },
        {
          type: 'paragraph',
          text: 'The scope, deliverables and specific conditions for each engagement will be defined in the corresponding order, proposal, or agreement accepted by the Client.',
        },
      ],
    },
    {
      id: 'nature',
      title: '3. Nature of Services (No Guarantees)',
      blocks: [
        {
          type: 'paragraph',
          text: 'GLC provides recommendations based on available data, professional judgment, and industry best practices.',
        },
        {
          type: 'paragraph',
          text: 'All Deliverables are advisory in nature and do not constitute guarantees of business outcomes, performance, revenue, or specific results. The Client remains solely responsible for its business decisions and implementation of any recommendations.',
        },
        {
          type: 'paragraph',
          text: 'Nothing in these Terms excludes or limits any liability that cannot be excluded or limited under mandatory Spanish law.',
        },
      ],
    },
    {
      id: 'client-responsibilities',
      title: '4. Client Responsibilities',
      blocks: [
        {
          type: 'paragraph',
          text: 'The Client agrees to:',
        },
        {
          type: 'list',
          items: [
            'provide accurate, complete and up-to-date information reasonably necessary for the performance of the Service',
            'ensure that it has a valid legal basis and the legal right to share any Data, including personal data, with GLC',
            'ensure that any personal data provided has been collected in compliance with applicable data protection laws',
            'comply with any applicable laws, regulations and industry standards in connection with the use of the Service and Deliverables',
            'not submit unlawful, infringing, or harmful content (including content that violates intellectual property or privacy rights)',
          ],
        },
        {
          type: 'paragraph',
          text: 'The Client is responsible for decisions taken on the basis of the Deliverables.',
        },
      ],
    },
    {
      id: 'data-protection',
      title: '5. Data Usage and Data Protection',
      blocks: [
        {
          type: 'paragraph',
          text: 'GLC processes Client Data solely for the purpose of providing and maintaining the Service, improving its quality, and fulfilling legal obligations.',
        },
        {
          type: 'paragraph',
          text: 'The detailed information on the processing of personal data is set out in GLC\'s Privacy Policy, which forms part of these Terms. Where GLC acts as data processor, the processing will also be governed by the DPA executed between GLC and the Client.',
        },
        {
          type: 'paragraph',
          text: 'GLC may use third-party providers and sub-processors (e.g., cloud infrastructure, email, analytics, AI providers) under appropriate contractual and security safeguards. An up-to-date list of main processors and sub-processors may be made available to Clients on request or via the website.',
        },
      ],
    },
    {
      id: 'confidentiality',
      title: '6. Confidentiality',
      blocks: [
        {
          type: 'paragraph',
          text: 'GLC will treat as confidential all Client Data and business information disclosed in connection with the Service, and will not disclose it to third parties except:',
        },
        {
          type: 'list',
          items: [
            'where necessary to provide the Service (e.g., to authorized sub-processors), subject to confidentiality obligations equivalent to those set out herein',
            'where the Client has given prior consent',
            'where required by law, regulation, court order, or request of a competent authority',
          ],
        },
        {
          type: 'paragraph',
          text: 'GLC will implement appropriate technical and organizational measures designed to protect the confidentiality, integrity and availability of Client Data.',
        },
        {
          type: 'paragraph',
          text: 'The Client also undertakes to keep confidential any non-public information received from GLC, including methodologies, pricing, and internal documentation.',
        },
      ],
    },
    {
      id: 'intellectual-property',
      title: '7. Intellectual Property',
      subsections: [
        {
          id: 'glc-ip',
          title: '7.1. GLC IP',
          blocks: [
            {
              type: 'paragraph',
              text: 'All methodologies, frameworks, tools, software, templates, know-how and internal systems used to provide the Service are and shall remain the exclusive property of GLC or its licensors.',
            },
            {
              type: 'paragraph',
              text: 'Nothing in these Terms shall be construed as a transfer of ownership of such intellectual property rights to the Client.',
            },
          ],
        },
        {
          id: 'deliverables-license',
          title: '7.2. Deliverables',
          blocks: [
            {
              type: 'paragraph',
              text: 'Subject to full payment of the applicable fees, the Client receives a non-exclusive, non-transferable, non-sublicensable license to use the Deliverables for its own internal business purposes.',
            },
            {
              type: 'paragraph',
              text: 'If the Client wishes to share or reproduce Deliverables with third parties (e.g., investors, partners), it shall ensure that such sharing does not infringe GLC\'s intellectual property and, where necessary, obtain GLC\'s prior written consent.',
            },
            {
              type: 'paragraph',
              text: 'GLC may reuse on an anonymous and aggregated basis insights, learnings and know-how derived from the engagement to improve its services and develop new offerings, provided that no Client confidential information or personal data is disclosed.',
            },
          ],
        },
      ],
    },
    {
      id: 'limitation-of-liability',
      title: '8. Limitation of Liability',
      blocks: [
        {
          type: 'paragraph',
          text: 'To the maximum extent permitted by law:',
        },
        {
          type: 'list',
          items: [
            'GLC shall not be liable for any indirect, incidental, special, consequential, punitive or loss-of-profit damages arising from or related to the Service or Deliverables.',
            'GLC shall not be responsible for business decisions made by the Client, whether or not based on the Deliverables.',
            'The total aggregate liability of GLC arising out of or in connection with the Service, whether in contract, tort or otherwise, shall be limited to the total amount actually paid by the Client to GLC for the specific Service giving rise to the claim.',
          ],
        },
        {
          type: 'paragraph',
          text: 'The above limitations shall not apply in cases of wilful misconduct (dolo) or gross negligence (culpa grave), nor where liability cannot be limited under mandatory Spanish law.',
        },
      ],
    },
    {
      id: 'fees',
      title: '9. Fees and Payment',
      blocks: [
        {
          type: 'list',
          items: [
            'Unless expressly stated otherwise, the Services are provided on a paid basis according to the pricing communicated to the Client.',
            'Fees, billing cycles and payment terms will be defined in the applicable proposal, order form, or agreement.',
            INVOICE_PAYMENT_SENTENCE,
            'In case of non-payment or serious delay, GLC may suspend or limit the provision of the Service until full payment is received, without prejudice to any other remedies available.',
          ],
        },
      ],
    },
    {
      id: 'term',
      title: '10. Term and Termination',
      blocks: [
        {
          type: 'paragraph',
          text: 'These Terms apply for as long as the Client uses the Service or until terminated in accordance with this section.',
        },
        {
          type: 'paragraph',
          text: 'GLC may suspend or terminate access to the Service, in whole or in part, with immediate effect if:',
        },
        {
          type: 'list',
          items: [
            'the Client materially breaches these Terms and does not remedy such breach within a reasonable period after written notice, or',
            'the Client fails to comply with its payment obligations.',
          ],
        },
        {
          type: 'paragraph',
          text: 'The Client may stop using the Service at any time and, where applicable, terminate the contractual relationship by written notice to GLC, subject to payment of any fees due for Services already performed.',
        },
        {
          type: 'paragraph',
          text: 'Termination shall not affect:',
        },
        {
          type: 'list',
          items: [
            'the Client\'s obligation to pay for Services already provided,',
            'the provisions on confidentiality, intellectual property, limitation of liability and data protection, which shall survive termination.',
          ],
        },
      ],
    },
    {
      id: 'dpa',
      title: '11. Data Processing Agreement (DPA)',
      blocks: [
        {
          type: 'paragraph',
          text: 'Where GLC processes personal data on behalf of the Client in the context of the Service, the parties shall enter into a Data Processing Agreement (DPA) in compliance with Article 28 of the GDPR.',
        },
        {
          type: 'paragraph',
          text: 'In case of conflict between these Terms and the DPA with respect to the processing of personal data, the DPA shall prevail.',
        },
      ],
    },
    {
      id: 'changes',
      title: '12. Changes to the Terms',
      blocks: [
        {
          type: 'paragraph',
          text: 'GLC may update these Terms from time to time, for example to reflect changes in the Service or in applicable law.',
        },
        {
          type: 'paragraph',
          text: 'Material changes will be communicated by reasonable means (e.g., on the website or via email). Continued use of the Service after the effective date of the updated Terms constitutes acceptance of such changes.',
        },
      ],
    },
    {
      id: 'governing-law',
      title: '13. Governing Law and Jurisdiction',
      blocks: [
        {
          type: 'paragraph',
          text: 'These Terms shall be governed by and construed in accordance with the laws of Spain.',
        },
        {
          type: 'paragraph',
          text: 'Any dispute arising out of or in connection with these Terms shall be submitted to the exclusive jurisdiction of the Courts of Palma de Mallorca, Spain, unless mandatory law provides otherwise.',
        },
      ],
    },
  ] as const satisfies readonly TermsSection[],
} as const;
